// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ApiPrecautionsConfig.proto
// Protobuf C++ Version: 5.29.5

#include "ApiPrecautionsConfig.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr ApiPrecautionsConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bypassorderprecautions_{false},
        bypassbondwarning_{false},
        bypassnegativeyieldconfirmation_{false},
        bypasscalledbondwarning_{false},
        bypasssameactionpairtradewarning_{false},
        bypassflaggedaccountswarning_{false},
        bypasspricebasedvolatilitywarning_{false},
        bypassredirectorderwarning_{false},
        bypassnooverfillprotection_{false},
        bypassroutemarketabletobbo_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ApiPrecautionsConfig::ApiPrecautionsConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ApiPrecautionsConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ApiPrecautionsConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ApiPrecautionsConfigDefaultTypeInternal() {}
  union {
    ApiPrecautionsConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApiPrecautionsConfigDefaultTypeInternal _ApiPrecautionsConfig_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ApiPrecautionsConfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ApiPrecautionsConfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_ApiPrecautionsConfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassorderprecautions_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassbondwarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassnegativeyieldconfirmation_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypasscalledbondwarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypasssameactionpairtradewarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassflaggedaccountswarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypasspricebasedvolatilitywarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassredirectorderwarning_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassnooverfillprotection_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ApiPrecautionsConfig, _impl_.bypassroutemarketabletobbo_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 18, -1, sizeof(::protobuf::ApiPrecautionsConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_ApiPrecautionsConfig_default_instance_._instance,
};
const char descriptor_table_protodef_ApiPrecautionsConfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032ApiPrecautionsConfig.proto\022\010protobuf\"\356"
    "\005\n\024ApiPrecautionsConfig\022#\n\026bypassOrderPr"
    "ecautions\030\001 \001(\010H\000\210\001\001\022\036\n\021bypassBondWarnin"
    "g\030\002 \001(\010H\001\210\001\001\022,\n\037bypassNegativeYieldConfi"
    "rmation\030\003 \001(\010H\002\210\001\001\022$\n\027bypassCalledBondWa"
    "rning\030\004 \001(\010H\003\210\001\001\022-\n bypassSameActionPair"
    "TradeWarning\030\005 \001(\010H\004\210\001\001\022)\n\034bypassFlagged"
    "AccountsWarning\030\006 \001(\010H\005\210\001\001\022.\n!bypassPric"
    "eBasedVolatilityWarning\030\007 \001(\010H\006\210\001\001\022\'\n\032by"
    "passRedirectOrderWarning\030\010 \001(\010H\007\210\001\001\022\'\n\032b"
    "ypassNoOverfillProtection\030\t \001(\010H\010\210\001\001\022\'\n\032"
    "bypassRouteMarketableToBBO\030\n \001(\010H\t\210\001\001B\031\n"
    "\027_bypassOrderPrecautionsB\024\n\022_bypassBondW"
    "arningB\"\n _bypassNegativeYieldConfirmati"
    "onB\032\n\030_bypassCalledBondWarningB#\n!_bypas"
    "sSameActionPairTradeWarningB\037\n\035_bypassFl"
    "aggedAccountsWarningB$\n\"_bypassPriceBase"
    "dVolatilityWarningB\035\n\033_bypassRedirectOrd"
    "erWarningB\035\n\033_bypassNoOverfillProtection"
    "B\035\n\033_bypassRouteMarketableToBBOBD\n\026com.i"
    "b.client.protobufB\031ApiPrecautionsConfigP"
    "roto\252\002\016IBApi.protobufb\006proto3"
};
static ::absl::once_flag descriptor_table_ApiPrecautionsConfig_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ApiPrecautionsConfig_2eproto = {
    false,
    false,
    869,
    descriptor_table_protodef_ApiPrecautionsConfig_2eproto,
    "ApiPrecautionsConfig.proto",
    &descriptor_table_ApiPrecautionsConfig_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ApiPrecautionsConfig_2eproto::offsets,
    file_level_enum_descriptors_ApiPrecautionsConfig_2eproto,
    file_level_service_descriptors_ApiPrecautionsConfig_2eproto,
};
namespace protobuf {
// ===================================================================

class ApiPrecautionsConfig::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ApiPrecautionsConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_._has_bits_);
};

ApiPrecautionsConfig::ApiPrecautionsConfig(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.ApiPrecautionsConfig)
}
ApiPrecautionsConfig::ApiPrecautionsConfig(
    ::google::protobuf::Arena* arena, const ApiPrecautionsConfig& from)
    : ApiPrecautionsConfig(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ApiPrecautionsConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ApiPrecautionsConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, bypassorderprecautions_),
           0,
           offsetof(Impl_, bypassroutemarketabletobbo_) -
               offsetof(Impl_, bypassorderprecautions_) +
               sizeof(Impl_::bypassroutemarketabletobbo_));
}
ApiPrecautionsConfig::~ApiPrecautionsConfig() {
  // @@protoc_insertion_point(destructor:protobuf.ApiPrecautionsConfig)
  SharedDtor(*this);
}
inline void ApiPrecautionsConfig::SharedDtor(MessageLite& self) {
  ApiPrecautionsConfig& this_ = static_cast<ApiPrecautionsConfig&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ApiPrecautionsConfig::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ApiPrecautionsConfig(arena);
}
constexpr auto ApiPrecautionsConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ApiPrecautionsConfig),
                                            alignof(ApiPrecautionsConfig));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ApiPrecautionsConfig::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ApiPrecautionsConfig_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ApiPrecautionsConfig::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ApiPrecautionsConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ApiPrecautionsConfig::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ApiPrecautionsConfig>(), &ApiPrecautionsConfig::ByteSizeLong,
            &ApiPrecautionsConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_._cached_size_),
        false,
    },
    &ApiPrecautionsConfig::kDescriptorMethods,
    &descriptor_table_ApiPrecautionsConfig_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ApiPrecautionsConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2> ApiPrecautionsConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::ApiPrecautionsConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bool bypassOrderPrecautions = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassorderprecautions_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassorderprecautions_)}},
    // optional bool bypassBondWarning = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassbondwarning_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassbondwarning_)}},
    // optional bool bypassNegativeYieldConfirmation = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassnegativeyieldconfirmation_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassnegativeyieldconfirmation_)}},
    // optional bool bypassCalledBondWarning = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypasscalledbondwarning_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasscalledbondwarning_)}},
    // optional bool bypassSameActionPairTradeWarning = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypasssameactionpairtradewarning_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasssameactionpairtradewarning_)}},
    // optional bool bypassFlaggedAccountsWarning = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassflaggedaccountswarning_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassflaggedaccountswarning_)}},
    // optional bool bypassPriceBasedVolatilityWarning = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypasspricebasedvolatilitywarning_), 6>(),
     {56, 6, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasspricebasedvolatilitywarning_)}},
    // optional bool bypassRedirectOrderWarning = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassredirectorderwarning_), 7>(),
     {64, 7, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassredirectorderwarning_)}},
    // optional bool bypassNoOverfillProtection = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassnooverfillprotection_), 8>(),
     {72, 8, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassnooverfillprotection_)}},
    // optional bool bypassRouteMarketableToBBO = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ApiPrecautionsConfig, _impl_.bypassroutemarketabletobbo_), 9>(),
     {80, 9, 0, PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassroutemarketabletobbo_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool bypassOrderPrecautions = 1;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassorderprecautions_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassBondWarning = 2;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassbondwarning_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassNegativeYieldConfirmation = 3;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassnegativeyieldconfirmation_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassCalledBondWarning = 4;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasscalledbondwarning_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassSameActionPairTradeWarning = 5;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasssameactionpairtradewarning_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassFlaggedAccountsWarning = 6;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassflaggedaccountswarning_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassPriceBasedVolatilityWarning = 7;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypasspricebasedvolatilitywarning_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassRedirectOrderWarning = 8;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassredirectorderwarning_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassNoOverfillProtection = 9;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassnooverfillprotection_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool bypassRouteMarketableToBBO = 10;
    {PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassroutemarketabletobbo_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ApiPrecautionsConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.ApiPrecautionsConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.bypassorderprecautions_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.bypassredirectorderwarning_) -
        reinterpret_cast<char*>(&_impl_.bypassorderprecautions_)) + sizeof(_impl_.bypassredirectorderwarning_));
  }
  if (cached_has_bits & 0x00000300u) {
    ::memset(&_impl_.bypassnooverfillprotection_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.bypassroutemarketabletobbo_) -
        reinterpret_cast<char*>(&_impl_.bypassnooverfillprotection_)) + sizeof(_impl_.bypassroutemarketabletobbo_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ApiPrecautionsConfig::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ApiPrecautionsConfig& this_ = static_cast<const ApiPrecautionsConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ApiPrecautionsConfig::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ApiPrecautionsConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.ApiPrecautionsConfig)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional bool bypassOrderPrecautions = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_bypassorderprecautions(), target);
          }

          // optional bool bypassBondWarning = 2;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_bypassbondwarning(), target);
          }

          // optional bool bypassNegativeYieldConfirmation = 3;
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_bypassnegativeyieldconfirmation(), target);
          }

          // optional bool bypassCalledBondWarning = 4;
          if (cached_has_bits & 0x00000008u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_bypasscalledbondwarning(), target);
          }

          // optional bool bypassSameActionPairTradeWarning = 5;
          if (cached_has_bits & 0x00000010u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_bypasssameactionpairtradewarning(), target);
          }

          // optional bool bypassFlaggedAccountsWarning = 6;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_bypassflaggedaccountswarning(), target);
          }

          // optional bool bypassPriceBasedVolatilityWarning = 7;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_bypasspricebasedvolatilitywarning(), target);
          }

          // optional bool bypassRedirectOrderWarning = 8;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                8, this_._internal_bypassredirectorderwarning(), target);
          }

          // optional bool bypassNoOverfillProtection = 9;
          if (cached_has_bits & 0x00000100u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_bypassnooverfillprotection(), target);
          }

          // optional bool bypassRouteMarketableToBBO = 10;
          if (cached_has_bits & 0x00000200u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                10, this_._internal_bypassroutemarketabletobbo(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.ApiPrecautionsConfig)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ApiPrecautionsConfig::ByteSizeLong(const MessageLite& base) {
          const ApiPrecautionsConfig& this_ = static_cast<const ApiPrecautionsConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ApiPrecautionsConfig::ByteSizeLong() const {
          const ApiPrecautionsConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.ApiPrecautionsConfig)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional bool bypassOrderPrecautions = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 2;
            }
            // optional bool bypassBondWarning = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 2;
            }
            // optional bool bypassNegativeYieldConfirmation = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 2;
            }
            // optional bool bypassCalledBondWarning = 4;
            if (cached_has_bits & 0x00000008u) {
              total_size += 2;
            }
            // optional bool bypassSameActionPairTradeWarning = 5;
            if (cached_has_bits & 0x00000010u) {
              total_size += 2;
            }
            // optional bool bypassFlaggedAccountsWarning = 6;
            if (cached_has_bits & 0x00000020u) {
              total_size += 2;
            }
            // optional bool bypassPriceBasedVolatilityWarning = 7;
            if (cached_has_bits & 0x00000040u) {
              total_size += 2;
            }
            // optional bool bypassRedirectOrderWarning = 8;
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
          if (cached_has_bits & 0x00000300u) {
            // optional bool bypassNoOverfillProtection = 9;
            if (cached_has_bits & 0x00000100u) {
              total_size += 2;
            }
            // optional bool bypassRouteMarketableToBBO = 10;
            if (cached_has_bits & 0x00000200u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ApiPrecautionsConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ApiPrecautionsConfig*>(&to_msg);
  auto& from = static_cast<const ApiPrecautionsConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.ApiPrecautionsConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.bypassorderprecautions_ = from._impl_.bypassorderprecautions_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.bypassbondwarning_ = from._impl_.bypassbondwarning_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.bypassnegativeyieldconfirmation_ = from._impl_.bypassnegativeyieldconfirmation_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.bypasscalledbondwarning_ = from._impl_.bypasscalledbondwarning_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.bypasssameactionpairtradewarning_ = from._impl_.bypasssameactionpairtradewarning_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.bypassflaggedaccountswarning_ = from._impl_.bypassflaggedaccountswarning_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.bypasspricebasedvolatilitywarning_ = from._impl_.bypasspricebasedvolatilitywarning_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.bypassredirectorderwarning_ = from._impl_.bypassredirectorderwarning_;
    }
  }
  if (cached_has_bits & 0x00000300u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.bypassnooverfillprotection_ = from._impl_.bypassnooverfillprotection_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.bypassroutemarketabletobbo_ = from._impl_.bypassroutemarketabletobbo_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ApiPrecautionsConfig::CopyFrom(const ApiPrecautionsConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.ApiPrecautionsConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ApiPrecautionsConfig::InternalSwap(ApiPrecautionsConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassroutemarketabletobbo_)
      + sizeof(ApiPrecautionsConfig::_impl_.bypassroutemarketabletobbo_)
      - PROTOBUF_FIELD_OFFSET(ApiPrecautionsConfig, _impl_.bypassorderprecautions_)>(
          reinterpret_cast<char*>(&_impl_.bypassorderprecautions_),
          reinterpret_cast<char*>(&other->_impl_.bypassorderprecautions_));
}

::google::protobuf::Metadata ApiPrecautionsConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ApiPrecautionsConfig_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
