// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CalculateOptionPriceRequest.proto
// Protobuf C++ Version: 5.29.5

#ifndef CalculateOptionPriceRequest_2eproto_2epb_2eh
#define CalculateOptionPriceRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "Contract.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_CalculateOptionPriceRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_CalculateOptionPriceRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_CalculateOptionPriceRequest_2eproto;
namespace protobuf {
class CalculateOptionPriceRequest;
struct CalculateOptionPriceRequestDefaultTypeInternal;
extern CalculateOptionPriceRequestDefaultTypeInternal _CalculateOptionPriceRequest_default_instance_;
class CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse;
struct CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUseDefaultTypeInternal;
extern CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUseDefaultTypeInternal _CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse*>(
        &_CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_CalculateOptionPriceRequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      77, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class CalculateOptionPriceRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.CalculateOptionPriceRequest) */ {
 public:
  inline CalculateOptionPriceRequest() : CalculateOptionPriceRequest(nullptr) {}
  ~CalculateOptionPriceRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CalculateOptionPriceRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CalculateOptionPriceRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalculateOptionPriceRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline CalculateOptionPriceRequest(const CalculateOptionPriceRequest& from) : CalculateOptionPriceRequest(nullptr, from) {}
  inline CalculateOptionPriceRequest(CalculateOptionPriceRequest&& from) noexcept
      : CalculateOptionPriceRequest(nullptr, std::move(from)) {}
  inline CalculateOptionPriceRequest& operator=(const CalculateOptionPriceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculateOptionPriceRequest& operator=(CalculateOptionPriceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculateOptionPriceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CalculateOptionPriceRequest* internal_default_instance() {
    return reinterpret_cast<const CalculateOptionPriceRequest*>(
        &_CalculateOptionPriceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CalculateOptionPriceRequest& a, CalculateOptionPriceRequest& b) { a.Swap(&b); }
  inline void Swap(CalculateOptionPriceRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculateOptionPriceRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculateOptionPriceRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CalculateOptionPriceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculateOptionPriceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalculateOptionPriceRequest& from) { CalculateOptionPriceRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CalculateOptionPriceRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.CalculateOptionPriceRequest"; }

 protected:
  explicit CalculateOptionPriceRequest(::google::protobuf::Arena* arena);
  CalculateOptionPriceRequest(::google::protobuf::Arena* arena, const CalculateOptionPriceRequest& from);
  CalculateOptionPriceRequest(::google::protobuf::Arena* arena, CalculateOptionPriceRequest&& from) noexcept
      : CalculateOptionPriceRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOptionPriceOptionsFieldNumber = 5,
    kContractFieldNumber = 2,
    kVolatilityFieldNumber = 3,
    kUnderPriceFieldNumber = 4,
    kReqIdFieldNumber = 1,
  };
  // map<string, string> optionPriceOptions = 5;
  int optionpriceoptions_size() const;
  private:
  int _internal_optionpriceoptions_size() const;

  public:
  void clear_optionpriceoptions() ;
  const ::google::protobuf::Map<std::string, std::string>& optionpriceoptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_optionpriceoptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_optionpriceoptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_optionpriceoptions();

  public:
  // optional .protobuf.Contract contract = 2;
  bool has_contract() const;
  void clear_contract() ;
  const ::protobuf::Contract& contract() const;
  PROTOBUF_NODISCARD ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* value);
  void unsafe_arena_set_allocated_contract(::protobuf::Contract* value);
  ::protobuf::Contract* unsafe_arena_release_contract();

  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();

  public:
  // optional double volatility = 3;
  bool has_volatility() const;
  void clear_volatility() ;
  double volatility() const;
  void set_volatility(double value);

  private:
  double _internal_volatility() const;
  void _internal_set_volatility(double value);

  public:
  // optional double underPrice = 4;
  bool has_underprice() const;
  void clear_underprice() ;
  double underprice() const;
  void set_underprice(double value);

  private:
  double _internal_underprice() const;
  void _internal_set_underprice(double value);

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.CalculateOptionPriceRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 5, 2,
      63, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CalculateOptionPriceRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<CalculateOptionPriceRequest_OptionPriceOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        optionpriceoptions_;
    ::protobuf::Contract* contract_;
    double volatility_;
    double underprice_;
    ::int32_t reqid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CalculateOptionPriceRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// CalculateOptionPriceRequest

// optional int32 reqId = 1;
inline bool CalculateOptionPriceRequest::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void CalculateOptionPriceRequest::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t CalculateOptionPriceRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.CalculateOptionPriceRequest.reqId)
  return _internal_reqid();
}
inline void CalculateOptionPriceRequest::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.CalculateOptionPriceRequest.reqId)
}
inline ::int32_t CalculateOptionPriceRequest::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void CalculateOptionPriceRequest::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.Contract contract = 2;
inline bool CalculateOptionPriceRequest::has_contract() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contract_ != nullptr);
  return value;
}
inline const ::protobuf::Contract& CalculateOptionPriceRequest::_internal_contract() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::Contract* p = _impl_.contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::Contract&>(::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& CalculateOptionPriceRequest::contract() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.CalculateOptionPriceRequest.contract)
  return _internal_contract();
}
inline void CalculateOptionPriceRequest::unsafe_arena_set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }
  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.CalculateOptionPriceRequest.contract)
}
inline ::protobuf::Contract* CalculateOptionPriceRequest::release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::Contract* released = _impl_.contract_;
  _impl_.contract_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::Contract* CalculateOptionPriceRequest::unsafe_arena_release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.CalculateOptionPriceRequest.contract)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::Contract* temp = _impl_.contract_;
  _impl_.contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* CalculateOptionPriceRequest::_internal_mutable_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::Contract>(GetArena());
    _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(p);
  }
  return _impl_.contract_;
}
inline ::protobuf::Contract* CalculateOptionPriceRequest::mutable_contract() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::protobuf::Contract* _msg = _internal_mutable_contract();
  // @@protoc_insertion_point(field_mutable:protobuf.CalculateOptionPriceRequest.contract)
  return _msg;
}
inline void CalculateOptionPriceRequest::set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.CalculateOptionPriceRequest.contract)
}

// optional double volatility = 3;
inline bool CalculateOptionPriceRequest::has_volatility() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CalculateOptionPriceRequest::clear_volatility() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.volatility_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double CalculateOptionPriceRequest::volatility() const {
  // @@protoc_insertion_point(field_get:protobuf.CalculateOptionPriceRequest.volatility)
  return _internal_volatility();
}
inline void CalculateOptionPriceRequest::set_volatility(double value) {
  _internal_set_volatility(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:protobuf.CalculateOptionPriceRequest.volatility)
}
inline double CalculateOptionPriceRequest::_internal_volatility() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.volatility_;
}
inline void CalculateOptionPriceRequest::_internal_set_volatility(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.volatility_ = value;
}

// optional double underPrice = 4;
inline bool CalculateOptionPriceRequest::has_underprice() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void CalculateOptionPriceRequest::clear_underprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double CalculateOptionPriceRequest::underprice() const {
  // @@protoc_insertion_point(field_get:protobuf.CalculateOptionPriceRequest.underPrice)
  return _internal_underprice();
}
inline void CalculateOptionPriceRequest::set_underprice(double value) {
  _internal_set_underprice(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:protobuf.CalculateOptionPriceRequest.underPrice)
}
inline double CalculateOptionPriceRequest::_internal_underprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.underprice_;
}
inline void CalculateOptionPriceRequest::_internal_set_underprice(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underprice_ = value;
}

// map<string, string> optionPriceOptions = 5;
inline int CalculateOptionPriceRequest::_internal_optionpriceoptions_size() const {
  return _internal_optionpriceoptions().size();
}
inline int CalculateOptionPriceRequest::optionpriceoptions_size() const {
  return _internal_optionpriceoptions_size();
}
inline void CalculateOptionPriceRequest::clear_optionpriceoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.optionpriceoptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& CalculateOptionPriceRequest::_internal_optionpriceoptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.optionpriceoptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& CalculateOptionPriceRequest::optionpriceoptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.CalculateOptionPriceRequest.optionPriceOptions)
  return _internal_optionpriceoptions();
}
inline ::google::protobuf::Map<std::string, std::string>* CalculateOptionPriceRequest::_internal_mutable_optionpriceoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.optionpriceoptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* CalculateOptionPriceRequest::mutable_optionpriceoptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.CalculateOptionPriceRequest.optionPriceOptions)
  return _internal_mutable_optionpriceoptions();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // CalculateOptionPriceRequest_2eproto_2epb_2eh
