// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ConfigResponse.proto
// Protobuf C++ Version: 5.29.5

#ifndef ConfigResponse_2eproto_2epb_2eh
#define ConfigResponse_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "LockAndExitConfig.pb.h"
#include "MessageConfig.pb.h"
#include "ApiConfig.pb.h"
#include "OrdersConfig.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ConfigResponse_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ConfigResponse_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ConfigResponse_2eproto;
namespace protobuf {
class ConfigResponse;
struct ConfigResponseDefaultTypeInternal;
extern ConfigResponseDefaultTypeInternal _ConfigResponse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ConfigResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.ConfigResponse) */ {
 public:
  inline ConfigResponse() : ConfigResponse(nullptr) {}
  ~ConfigResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConfigResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConfigResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConfigResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ConfigResponse(const ConfigResponse& from) : ConfigResponse(nullptr, from) {}
  inline ConfigResponse(ConfigResponse&& from) noexcept
      : ConfigResponse(nullptr, std::move(from)) {}
  inline ConfigResponse& operator=(const ConfigResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigResponse& operator=(ConfigResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConfigResponse* internal_default_instance() {
    return reinterpret_cast<const ConfigResponse*>(
        &_ConfigResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ConfigResponse& a, ConfigResponse& b) { a.Swap(&b); }
  inline void Swap(ConfigResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConfigResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConfigResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConfigResponse& from) { ConfigResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConfigResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.ConfigResponse"; }

 protected:
  explicit ConfigResponse(::google::protobuf::Arena* arena);
  ConfigResponse(::google::protobuf::Arena* arena, const ConfigResponse& from);
  ConfigResponse(::google::protobuf::Arena* arena, ConfigResponse&& from) noexcept
      : ConfigResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessagesFieldNumber = 3,
    kLockAndExitFieldNumber = 2,
    kApiFieldNumber = 4,
    kOrdersFieldNumber = 5,
    kReqIdFieldNumber = 1,
  };
  // repeated .protobuf.MessageConfig messages = 3;
  int messages_size() const;
  private:
  int _internal_messages_size() const;

  public:
  void clear_messages() ;
  ::protobuf::MessageConfig* mutable_messages(int index);
  ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>* mutable_messages();

  private:
  const ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>& _internal_messages() const;
  ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>* _internal_mutable_messages();
  public:
  const ::protobuf::MessageConfig& messages(int index) const;
  ::protobuf::MessageConfig* add_messages();
  const ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>& messages() const;
  // optional .protobuf.LockAndExitConfig lockAndExit = 2;
  bool has_lockandexit() const;
  void clear_lockandexit() ;
  const ::protobuf::LockAndExitConfig& lockandexit() const;
  PROTOBUF_NODISCARD ::protobuf::LockAndExitConfig* release_lockandexit();
  ::protobuf::LockAndExitConfig* mutable_lockandexit();
  void set_allocated_lockandexit(::protobuf::LockAndExitConfig* value);
  void unsafe_arena_set_allocated_lockandexit(::protobuf::LockAndExitConfig* value);
  ::protobuf::LockAndExitConfig* unsafe_arena_release_lockandexit();

  private:
  const ::protobuf::LockAndExitConfig& _internal_lockandexit() const;
  ::protobuf::LockAndExitConfig* _internal_mutable_lockandexit();

  public:
  // optional .protobuf.ApiConfig api = 4;
  bool has_api() const;
  void clear_api() ;
  const ::protobuf::ApiConfig& api() const;
  PROTOBUF_NODISCARD ::protobuf::ApiConfig* release_api();
  ::protobuf::ApiConfig* mutable_api();
  void set_allocated_api(::protobuf::ApiConfig* value);
  void unsafe_arena_set_allocated_api(::protobuf::ApiConfig* value);
  ::protobuf::ApiConfig* unsafe_arena_release_api();

  private:
  const ::protobuf::ApiConfig& _internal_api() const;
  ::protobuf::ApiConfig* _internal_mutable_api();

  public:
  // optional .protobuf.OrdersConfig orders = 5;
  bool has_orders() const;
  void clear_orders() ;
  const ::protobuf::OrdersConfig& orders() const;
  PROTOBUF_NODISCARD ::protobuf::OrdersConfig* release_orders();
  ::protobuf::OrdersConfig* mutable_orders();
  void set_allocated_orders(::protobuf::OrdersConfig* value);
  void unsafe_arena_set_allocated_orders(::protobuf::OrdersConfig* value);
  ::protobuf::OrdersConfig* unsafe_arena_release_orders();

  private:
  const ::protobuf::OrdersConfig& _internal_orders() const;
  ::protobuf::OrdersConfig* _internal_mutable_orders();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.ConfigResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 4,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ConfigResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::protobuf::MessageConfig > messages_;
    ::protobuf::LockAndExitConfig* lockandexit_;
    ::protobuf::ApiConfig* api_;
    ::protobuf::OrdersConfig* orders_;
    ::int32_t reqid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ConfigResponse_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConfigResponse

// optional int32 reqId = 1;
inline bool ConfigResponse::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ConfigResponse::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t ConfigResponse::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.ConfigResponse.reqId)
  return _internal_reqid();
}
inline void ConfigResponse::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.ConfigResponse.reqId)
}
inline ::int32_t ConfigResponse::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void ConfigResponse::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.LockAndExitConfig lockAndExit = 2;
inline bool ConfigResponse::has_lockandexit() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.lockandexit_ != nullptr);
  return value;
}
inline const ::protobuf::LockAndExitConfig& ConfigResponse::_internal_lockandexit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::LockAndExitConfig* p = _impl_.lockandexit_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::LockAndExitConfig&>(::protobuf::_LockAndExitConfig_default_instance_);
}
inline const ::protobuf::LockAndExitConfig& ConfigResponse::lockandexit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ConfigResponse.lockAndExit)
  return _internal_lockandexit();
}
inline void ConfigResponse::unsafe_arena_set_allocated_lockandexit(::protobuf::LockAndExitConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.lockandexit_);
  }
  _impl_.lockandexit_ = reinterpret_cast<::protobuf::LockAndExitConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ConfigResponse.lockAndExit)
}
inline ::protobuf::LockAndExitConfig* ConfigResponse::release_lockandexit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::LockAndExitConfig* released = _impl_.lockandexit_;
  _impl_.lockandexit_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::LockAndExitConfig* ConfigResponse::unsafe_arena_release_lockandexit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ConfigResponse.lockAndExit)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::LockAndExitConfig* temp = _impl_.lockandexit_;
  _impl_.lockandexit_ = nullptr;
  return temp;
}
inline ::protobuf::LockAndExitConfig* ConfigResponse::_internal_mutable_lockandexit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.lockandexit_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::LockAndExitConfig>(GetArena());
    _impl_.lockandexit_ = reinterpret_cast<::protobuf::LockAndExitConfig*>(p);
  }
  return _impl_.lockandexit_;
}
inline ::protobuf::LockAndExitConfig* ConfigResponse::mutable_lockandexit() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::protobuf::LockAndExitConfig* _msg = _internal_mutable_lockandexit();
  // @@protoc_insertion_point(field_mutable:protobuf.ConfigResponse.lockAndExit)
  return _msg;
}
inline void ConfigResponse::set_allocated_lockandexit(::protobuf::LockAndExitConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.lockandexit_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.lockandexit_ = reinterpret_cast<::protobuf::LockAndExitConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.ConfigResponse.lockAndExit)
}

// repeated .protobuf.MessageConfig messages = 3;
inline int ConfigResponse::_internal_messages_size() const {
  return _internal_messages().size();
}
inline int ConfigResponse::messages_size() const {
  return _internal_messages_size();
}
inline ::protobuf::MessageConfig* ConfigResponse::mutable_messages(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:protobuf.ConfigResponse.messages)
  return _internal_mutable_messages()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>* ConfigResponse::mutable_messages()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:protobuf.ConfigResponse.messages)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_messages();
}
inline const ::protobuf::MessageConfig& ConfigResponse::messages(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ConfigResponse.messages)
  return _internal_messages().Get(index);
}
inline ::protobuf::MessageConfig* ConfigResponse::add_messages() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::protobuf::MessageConfig* _add = _internal_mutable_messages()->Add();
  // @@protoc_insertion_point(field_add:protobuf.ConfigResponse.messages)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>& ConfigResponse::messages() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:protobuf.ConfigResponse.messages)
  return _internal_messages();
}
inline const ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>&
ConfigResponse::_internal_messages() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.messages_;
}
inline ::google::protobuf::RepeatedPtrField<::protobuf::MessageConfig>*
ConfigResponse::_internal_mutable_messages() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.messages_;
}

// optional .protobuf.ApiConfig api = 4;
inline bool ConfigResponse::has_api() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.api_ != nullptr);
  return value;
}
inline const ::protobuf::ApiConfig& ConfigResponse::_internal_api() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::ApiConfig* p = _impl_.api_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::ApiConfig&>(::protobuf::_ApiConfig_default_instance_);
}
inline const ::protobuf::ApiConfig& ConfigResponse::api() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ConfigResponse.api)
  return _internal_api();
}
inline void ConfigResponse::unsafe_arena_set_allocated_api(::protobuf::ApiConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.api_);
  }
  _impl_.api_ = reinterpret_cast<::protobuf::ApiConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ConfigResponse.api)
}
inline ::protobuf::ApiConfig* ConfigResponse::release_api() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::ApiConfig* released = _impl_.api_;
  _impl_.api_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::ApiConfig* ConfigResponse::unsafe_arena_release_api() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ConfigResponse.api)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::ApiConfig* temp = _impl_.api_;
  _impl_.api_ = nullptr;
  return temp;
}
inline ::protobuf::ApiConfig* ConfigResponse::_internal_mutable_api() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.api_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::ApiConfig>(GetArena());
    _impl_.api_ = reinterpret_cast<::protobuf::ApiConfig*>(p);
  }
  return _impl_.api_;
}
inline ::protobuf::ApiConfig* ConfigResponse::mutable_api() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::protobuf::ApiConfig* _msg = _internal_mutable_api();
  // @@protoc_insertion_point(field_mutable:protobuf.ConfigResponse.api)
  return _msg;
}
inline void ConfigResponse::set_allocated_api(::protobuf::ApiConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.api_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.api_ = reinterpret_cast<::protobuf::ApiConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.ConfigResponse.api)
}

// optional .protobuf.OrdersConfig orders = 5;
inline bool ConfigResponse::has_orders() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.orders_ != nullptr);
  return value;
}
inline const ::protobuf::OrdersConfig& ConfigResponse::_internal_orders() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::OrdersConfig* p = _impl_.orders_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::OrdersConfig&>(::protobuf::_OrdersConfig_default_instance_);
}
inline const ::protobuf::OrdersConfig& ConfigResponse::orders() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ConfigResponse.orders)
  return _internal_orders();
}
inline void ConfigResponse::unsafe_arena_set_allocated_orders(::protobuf::OrdersConfig* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.orders_);
  }
  _impl_.orders_ = reinterpret_cast<::protobuf::OrdersConfig*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ConfigResponse.orders)
}
inline ::protobuf::OrdersConfig* ConfigResponse::release_orders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::protobuf::OrdersConfig* released = _impl_.orders_;
  _impl_.orders_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::OrdersConfig* ConfigResponse::unsafe_arena_release_orders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ConfigResponse.orders)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::protobuf::OrdersConfig* temp = _impl_.orders_;
  _impl_.orders_ = nullptr;
  return temp;
}
inline ::protobuf::OrdersConfig* ConfigResponse::_internal_mutable_orders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.orders_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::OrdersConfig>(GetArena());
    _impl_.orders_ = reinterpret_cast<::protobuf::OrdersConfig*>(p);
  }
  return _impl_.orders_;
}
inline ::protobuf::OrdersConfig* ConfigResponse::mutable_orders() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::protobuf::OrdersConfig* _msg = _internal_mutable_orders();
  // @@protoc_insertion_point(field_mutable:protobuf.ConfigResponse.orders)
  return _msg;
}
inline void ConfigResponse::set_allocated_orders(::protobuf::OrdersConfig* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.orders_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.orders_ = reinterpret_cast<::protobuf::OrdersConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.ConfigResponse.orders)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ConfigResponse_2eproto_2epb_2eh
