// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DepthMarketDataDescription.proto
// Protobuf C++ Version: 5.29.5

#ifndef DepthMarketDataDescription_2eproto_2epb_2eh
#define DepthMarketDataDescription_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DepthMarketDataDescription_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_DepthMarketDataDescription_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_DepthMarketDataDescription_2eproto;
namespace protobuf {
class DepthMarketDataDescription;
struct DepthMarketDataDescriptionDefaultTypeInternal;
extern DepthMarketDataDescriptionDefaultTypeInternal _DepthMarketDataDescription_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class DepthMarketDataDescription final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.DepthMarketDataDescription) */ {
 public:
  inline DepthMarketDataDescription() : DepthMarketDataDescription(nullptr) {}
  ~DepthMarketDataDescription() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DepthMarketDataDescription* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DepthMarketDataDescription));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DepthMarketDataDescription(
      ::google::protobuf::internal::ConstantInitialized);

  inline DepthMarketDataDescription(const DepthMarketDataDescription& from) : DepthMarketDataDescription(nullptr, from) {}
  inline DepthMarketDataDescription(DepthMarketDataDescription&& from) noexcept
      : DepthMarketDataDescription(nullptr, std::move(from)) {}
  inline DepthMarketDataDescription& operator=(const DepthMarketDataDescription& from) {
    CopyFrom(from);
    return *this;
  }
  inline DepthMarketDataDescription& operator=(DepthMarketDataDescription&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DepthMarketDataDescription& default_instance() {
    return *internal_default_instance();
  }
  static inline const DepthMarketDataDescription* internal_default_instance() {
    return reinterpret_cast<const DepthMarketDataDescription*>(
        &_DepthMarketDataDescription_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DepthMarketDataDescription& a, DepthMarketDataDescription& b) { a.Swap(&b); }
  inline void Swap(DepthMarketDataDescription* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DepthMarketDataDescription* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DepthMarketDataDescription* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DepthMarketDataDescription>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DepthMarketDataDescription& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DepthMarketDataDescription& from) { DepthMarketDataDescription::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DepthMarketDataDescription* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.DepthMarketDataDescription"; }

 protected:
  explicit DepthMarketDataDescription(::google::protobuf::Arena* arena);
  DepthMarketDataDescription(::google::protobuf::Arena* arena, const DepthMarketDataDescription& from);
  DepthMarketDataDescription(::google::protobuf::Arena* arena, DepthMarketDataDescription&& from) noexcept
      : DepthMarketDataDescription(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExchangeFieldNumber = 1,
    kSecTypeFieldNumber = 2,
    kListingExchFieldNumber = 3,
    kServiceDataTypeFieldNumber = 4,
    kAggGroupFieldNumber = 5,
  };
  // optional string exchange = 1;
  bool has_exchange() const;
  void clear_exchange() ;
  const std::string& exchange() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange(Arg_&& arg, Args_... args);
  std::string* mutable_exchange();
  PROTOBUF_NODISCARD std::string* release_exchange();
  void set_allocated_exchange(std::string* value);

  private:
  const std::string& _internal_exchange() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchange(
      const std::string& value);
  std::string* _internal_mutable_exchange();

  public:
  // optional string secType = 2;
  bool has_sectype() const;
  void clear_sectype() ;
  const std::string& sectype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sectype(Arg_&& arg, Args_... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* value);

  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(
      const std::string& value);
  std::string* _internal_mutable_sectype();

  public:
  // optional string listingExch = 3;
  bool has_listingexch() const;
  void clear_listingexch() ;
  const std::string& listingexch() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_listingexch(Arg_&& arg, Args_... args);
  std::string* mutable_listingexch();
  PROTOBUF_NODISCARD std::string* release_listingexch();
  void set_allocated_listingexch(std::string* value);

  private:
  const std::string& _internal_listingexch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_listingexch(
      const std::string& value);
  std::string* _internal_mutable_listingexch();

  public:
  // optional string serviceDataType = 4;
  bool has_servicedatatype() const;
  void clear_servicedatatype() ;
  const std::string& servicedatatype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_servicedatatype(Arg_&& arg, Args_... args);
  std::string* mutable_servicedatatype();
  PROTOBUF_NODISCARD std::string* release_servicedatatype();
  void set_allocated_servicedatatype(std::string* value);

  private:
  const std::string& _internal_servicedatatype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_servicedatatype(
      const std::string& value);
  std::string* _internal_mutable_servicedatatype();

  public:
  // optional int32 aggGroup = 5;
  bool has_agggroup() const;
  void clear_agggroup() ;
  ::int32_t agggroup() const;
  void set_agggroup(::int32_t value);

  private:
  ::int32_t _internal_agggroup() const;
  void _internal_set_agggroup(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.DepthMarketDataDescription)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      85, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DepthMarketDataDescription& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr exchange_;
    ::google::protobuf::internal::ArenaStringPtr sectype_;
    ::google::protobuf::internal::ArenaStringPtr listingexch_;
    ::google::protobuf::internal::ArenaStringPtr servicedatatype_;
    ::int32_t agggroup_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DepthMarketDataDescription_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DepthMarketDataDescription

// optional string exchange = 1;
inline bool DepthMarketDataDescription::has_exchange() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void DepthMarketDataDescription::clear_exchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DepthMarketDataDescription::exchange() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.DepthMarketDataDescription.exchange)
  return _internal_exchange();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DepthMarketDataDescription::set_exchange(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.exchange_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.DepthMarketDataDescription.exchange)
}
inline std::string* DepthMarketDataDescription::mutable_exchange() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_exchange();
  // @@protoc_insertion_point(field_mutable:protobuf.DepthMarketDataDescription.exchange)
  return _s;
}
inline const std::string& DepthMarketDataDescription::_internal_exchange() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exchange_.Get();
}
inline void DepthMarketDataDescription::_internal_set_exchange(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.exchange_.Set(value, GetArena());
}
inline std::string* DepthMarketDataDescription::_internal_mutable_exchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.exchange_.Mutable( GetArena());
}
inline std::string* DepthMarketDataDescription::release_exchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.DepthMarketDataDescription.exchange)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.exchange_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.exchange_.Set("", GetArena());
  }
  return released;
}
inline void DepthMarketDataDescription::set_allocated_exchange(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.exchange_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.exchange_.IsDefault()) {
    _impl_.exchange_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.DepthMarketDataDescription.exchange)
}

// optional string secType = 2;
inline bool DepthMarketDataDescription::has_sectype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void DepthMarketDataDescription::clear_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sectype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& DepthMarketDataDescription::sectype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.DepthMarketDataDescription.secType)
  return _internal_sectype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DepthMarketDataDescription::set_sectype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sectype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.DepthMarketDataDescription.secType)
}
inline std::string* DepthMarketDataDescription::mutable_sectype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:protobuf.DepthMarketDataDescription.secType)
  return _s;
}
inline const std::string& DepthMarketDataDescription::_internal_sectype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sectype_.Get();
}
inline void DepthMarketDataDescription::_internal_set_sectype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sectype_.Set(value, GetArena());
}
inline std::string* DepthMarketDataDescription::_internal_mutable_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.sectype_.Mutable( GetArena());
}
inline std::string* DepthMarketDataDescription::release_sectype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.DepthMarketDataDescription.secType)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.sectype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sectype_.Set("", GetArena());
  }
  return released;
}
inline void DepthMarketDataDescription::set_allocated_sectype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.sectype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sectype_.IsDefault()) {
    _impl_.sectype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.DepthMarketDataDescription.secType)
}

// optional string listingExch = 3;
inline bool DepthMarketDataDescription::has_listingexch() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void DepthMarketDataDescription::clear_listingexch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.listingexch_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& DepthMarketDataDescription::listingexch() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.DepthMarketDataDescription.listingExch)
  return _internal_listingexch();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DepthMarketDataDescription::set_listingexch(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.listingexch_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.DepthMarketDataDescription.listingExch)
}
inline std::string* DepthMarketDataDescription::mutable_listingexch() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_listingexch();
  // @@protoc_insertion_point(field_mutable:protobuf.DepthMarketDataDescription.listingExch)
  return _s;
}
inline const std::string& DepthMarketDataDescription::_internal_listingexch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.listingexch_.Get();
}
inline void DepthMarketDataDescription::_internal_set_listingexch(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.listingexch_.Set(value, GetArena());
}
inline std::string* DepthMarketDataDescription::_internal_mutable_listingexch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.listingexch_.Mutable( GetArena());
}
inline std::string* DepthMarketDataDescription::release_listingexch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.DepthMarketDataDescription.listingExch)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.listingexch_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.listingexch_.Set("", GetArena());
  }
  return released;
}
inline void DepthMarketDataDescription::set_allocated_listingexch(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.listingexch_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.listingexch_.IsDefault()) {
    _impl_.listingexch_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.DepthMarketDataDescription.listingExch)
}

// optional string serviceDataType = 4;
inline bool DepthMarketDataDescription::has_servicedatatype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void DepthMarketDataDescription::clear_servicedatatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servicedatatype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& DepthMarketDataDescription::servicedatatype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.DepthMarketDataDescription.serviceDataType)
  return _internal_servicedatatype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DepthMarketDataDescription::set_servicedatatype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.servicedatatype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.DepthMarketDataDescription.serviceDataType)
}
inline std::string* DepthMarketDataDescription::mutable_servicedatatype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_servicedatatype();
  // @@protoc_insertion_point(field_mutable:protobuf.DepthMarketDataDescription.serviceDataType)
  return _s;
}
inline const std::string& DepthMarketDataDescription::_internal_servicedatatype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.servicedatatype_.Get();
}
inline void DepthMarketDataDescription::_internal_set_servicedatatype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.servicedatatype_.Set(value, GetArena());
}
inline std::string* DepthMarketDataDescription::_internal_mutable_servicedatatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.servicedatatype_.Mutable( GetArena());
}
inline std::string* DepthMarketDataDescription::release_servicedatatype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.DepthMarketDataDescription.serviceDataType)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.servicedatatype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.servicedatatype_.Set("", GetArena());
  }
  return released;
}
inline void DepthMarketDataDescription::set_allocated_servicedatatype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.servicedatatype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.servicedatatype_.IsDefault()) {
    _impl_.servicedatatype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.DepthMarketDataDescription.serviceDataType)
}

// optional int32 aggGroup = 5;
inline bool DepthMarketDataDescription::has_agggroup() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void DepthMarketDataDescription::clear_agggroup() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agggroup_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t DepthMarketDataDescription::agggroup() const {
  // @@protoc_insertion_point(field_get:protobuf.DepthMarketDataDescription.aggGroup)
  return _internal_agggroup();
}
inline void DepthMarketDataDescription::set_agggroup(::int32_t value) {
  _internal_set_agggroup(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:protobuf.DepthMarketDataDescription.aggGroup)
}
inline ::int32_t DepthMarketDataDescription::_internal_agggroup() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.agggroup_;
}
inline void DepthMarketDataDescription::_internal_set_agggroup(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agggroup_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // DepthMarketDataDescription_2eproto_2epb_2eh
