// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ExerciseOptionsRequest.proto
// Protobuf C++ Version: 5.29.5

#include "ExerciseOptionsRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr ExerciseOptionsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        manualordertime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        customeraccount_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contract_{nullptr},
        orderid_{0},
        exerciseaction_{0},
        exercisequantity_{0},
        override_{false},
        professionalcustomer_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ExerciseOptionsRequest::ExerciseOptionsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExerciseOptionsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExerciseOptionsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExerciseOptionsRequestDefaultTypeInternal() {}
  union {
    ExerciseOptionsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExerciseOptionsRequestDefaultTypeInternal _ExerciseOptionsRequest_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ExerciseOptionsRequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ExerciseOptionsRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_ExerciseOptionsRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.orderid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.contract_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.exerciseaction_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.exercisequantity_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.account_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.override_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.manualordertime_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.customeraccount_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ExerciseOptionsRequest, _impl_.professionalcustomer_),
        4,
        3,
        5,
        6,
        0,
        7,
        1,
        2,
        8,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 17, -1, sizeof(::protobuf::ExerciseOptionsRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_ExerciseOptionsRequest_default_instance_._instance,
};
const char descriptor_table_protodef_ExerciseOptionsRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034ExerciseOptionsRequest.proto\022\010protobuf"
    "\032\016Contract.proto\"\274\003\n\026ExerciseOptionsRequ"
    "est\022\024\n\007orderId\030\001 \001(\005H\000\210\001\001\022)\n\010contract\030\002 "
    "\001(\0132\022.protobuf.ContractH\001\210\001\001\022\033\n\016exercise"
    "Action\030\003 \001(\005H\002\210\001\001\022\035\n\020exerciseQuantity\030\004 "
    "\001(\005H\003\210\001\001\022\024\n\007account\030\005 \001(\tH\004\210\001\001\022\025\n\010overri"
    "de\030\006 \001(\010H\005\210\001\001\022\034\n\017manualOrderTime\030\007 \001(\tH\006"
    "\210\001\001\022\034\n\017customerAccount\030\010 \001(\tH\007\210\001\001\022!\n\024pro"
    "fessionalCustomer\030\t \001(\010H\010\210\001\001B\n\n\010_orderId"
    "B\013\n\t_contractB\021\n\017_exerciseActionB\023\n\021_exe"
    "rciseQuantityB\n\n\010_accountB\013\n\t_overrideB\022"
    "\n\020_manualOrderTimeB\022\n\020_customerAccountB\027"
    "\n\025_professionalCustomerBF\n\026com.ib.client"
    ".protobufB\033ExerciseOptionsRequestProto\252\002"
    "\016IBApi.protobufb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ExerciseOptionsRequest_2eproto_deps[1] =
    {
        &::descriptor_table_Contract_2eproto,
};
static ::absl::once_flag descriptor_table_ExerciseOptionsRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ExerciseOptionsRequest_2eproto = {
    false,
    false,
    583,
    descriptor_table_protodef_ExerciseOptionsRequest_2eproto,
    "ExerciseOptionsRequest.proto",
    &descriptor_table_ExerciseOptionsRequest_2eproto_once,
    descriptor_table_ExerciseOptionsRequest_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_ExerciseOptionsRequest_2eproto::offsets,
    file_level_enum_descriptors_ExerciseOptionsRequest_2eproto,
    file_level_service_descriptors_ExerciseOptionsRequest_2eproto,
};
namespace protobuf {
// ===================================================================

class ExerciseOptionsRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ExerciseOptionsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_._has_bits_);
};

void ExerciseOptionsRequest::clear_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ != nullptr) _impl_.contract_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
ExerciseOptionsRequest::ExerciseOptionsRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.ExerciseOptionsRequest)
}
inline PROTOBUF_NDEBUG_INLINE ExerciseOptionsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::ExerciseOptionsRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        account_(arena, from.account_),
        manualordertime_(arena, from.manualordertime_),
        customeraccount_(arena, from.customeraccount_) {}

ExerciseOptionsRequest::ExerciseOptionsRequest(
    ::google::protobuf::Arena* arena,
    const ExerciseOptionsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ExerciseOptionsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.contract_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(
                              arena, *from._impl_.contract_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, orderid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, orderid_),
           offsetof(Impl_, professionalcustomer_) -
               offsetof(Impl_, orderid_) +
               sizeof(Impl_::professionalcustomer_));

  // @@protoc_insertion_point(copy_constructor:protobuf.ExerciseOptionsRequest)
}
inline PROTOBUF_NDEBUG_INLINE ExerciseOptionsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        account_(arena),
        manualordertime_(arena),
        customeraccount_(arena) {}

inline void ExerciseOptionsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, contract_),
           0,
           offsetof(Impl_, professionalcustomer_) -
               offsetof(Impl_, contract_) +
               sizeof(Impl_::professionalcustomer_));
}
ExerciseOptionsRequest::~ExerciseOptionsRequest() {
  // @@protoc_insertion_point(destructor:protobuf.ExerciseOptionsRequest)
  SharedDtor(*this);
}
inline void ExerciseOptionsRequest::SharedDtor(MessageLite& self) {
  ExerciseOptionsRequest& this_ = static_cast<ExerciseOptionsRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.account_.Destroy();
  this_._impl_.manualordertime_.Destroy();
  this_._impl_.customeraccount_.Destroy();
  delete this_._impl_.contract_;
  this_._impl_.~Impl_();
}

inline void* ExerciseOptionsRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ExerciseOptionsRequest(arena);
}
constexpr auto ExerciseOptionsRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ExerciseOptionsRequest),
                                            alignof(ExerciseOptionsRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ExerciseOptionsRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ExerciseOptionsRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ExerciseOptionsRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ExerciseOptionsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ExerciseOptionsRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ExerciseOptionsRequest>(), &ExerciseOptionsRequest::ByteSizeLong,
            &ExerciseOptionsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_._cached_size_),
        false,
    },
    &ExerciseOptionsRequest::kDescriptorMethods,
    &descriptor_table_ExerciseOptionsRequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ExerciseOptionsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 1, 85, 2> ExerciseOptionsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::ExerciseOptionsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 orderId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExerciseOptionsRequest, _impl_.orderid_), 4>(),
     {8, 4, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.orderid_)}},
    // optional .protobuf.Contract contract = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.contract_)}},
    // optional int32 exerciseAction = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExerciseOptionsRequest, _impl_.exerciseaction_), 5>(),
     {24, 5, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.exerciseaction_)}},
    // optional int32 exerciseQuantity = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExerciseOptionsRequest, _impl_.exercisequantity_), 6>(),
     {32, 6, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.exercisequantity_)}},
    // optional string account = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.account_)}},
    // optional bool override = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ExerciseOptionsRequest, _impl_.override_), 7>(),
     {48, 7, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.override_)}},
    // optional string manualOrderTime = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 1, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.manualordertime_)}},
    // optional string customerAccount = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 2, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.customeraccount_)}},
    // optional bool professionalCustomer = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ExerciseOptionsRequest, _impl_.professionalcustomer_), 8>(),
     {72, 8, 0, PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.professionalcustomer_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 orderId = 1;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.orderid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .protobuf.Contract contract = 2;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.contract_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 exerciseAction = 3;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.exerciseaction_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 exerciseQuantity = 4;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.exercisequantity_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string account = 5;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.account_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional bool override = 6;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.override_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional string manualOrderTime = 7;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.manualordertime_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string customerAccount = 8;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.customeraccount_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional bool professionalCustomer = 9;
    {PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.professionalcustomer_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::protobuf::Contract>()},
  }}, {{
    "\37\0\0\0\0\7\0\17\17\0\0\0\0\0\0\0"
    "protobuf.ExerciseOptionsRequest"
    "account"
    "manualOrderTime"
    "customerAccount"
  }},
};

PROTOBUF_NOINLINE void ExerciseOptionsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.ExerciseOptionsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.account_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.manualordertime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.customeraccount_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.contract_ != nullptr);
      _impl_.contract_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f0u) {
    ::memset(&_impl_.orderid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.override_) -
        reinterpret_cast<char*>(&_impl_.orderid_)) + sizeof(_impl_.override_));
  }
  _impl_.professionalcustomer_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ExerciseOptionsRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ExerciseOptionsRequest& this_ = static_cast<const ExerciseOptionsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ExerciseOptionsRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ExerciseOptionsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.ExerciseOptionsRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 orderId = 1;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_orderid(), target);
          }

          // optional .protobuf.Contract contract = 2;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.contract_, this_._impl_.contract_->GetCachedSize(), target,
                stream);
          }

          // optional int32 exerciseAction = 3;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_exerciseaction(), target);
          }

          // optional int32 exerciseQuantity = 4;
          if (cached_has_bits & 0x00000040u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_exercisequantity(), target);
          }

          // optional string account = 5;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_account();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.ExerciseOptionsRequest.account");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // optional bool override = 6;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_override(), target);
          }

          // optional string manualOrderTime = 7;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_manualordertime();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.ExerciseOptionsRequest.manualOrderTime");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // optional string customerAccount = 8;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_customeraccount();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.ExerciseOptionsRequest.customerAccount");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // optional bool professionalCustomer = 9;
          if (cached_has_bits & 0x00000100u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_professionalcustomer(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.ExerciseOptionsRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ExerciseOptionsRequest::ByteSizeLong(const MessageLite& base) {
          const ExerciseOptionsRequest& this_ = static_cast<const ExerciseOptionsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ExerciseOptionsRequest::ByteSizeLong() const {
          const ExerciseOptionsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.ExerciseOptionsRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string account = 5;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_account());
            }
            // optional string manualOrderTime = 7;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_manualordertime());
            }
            // optional string customerAccount = 8;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_customeraccount());
            }
            // optional .protobuf.Contract contract = 2;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.contract_);
            }
            // optional int32 orderId = 1;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_orderid());
            }
            // optional int32 exerciseAction = 3;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_exerciseaction());
            }
            // optional int32 exerciseQuantity = 4;
            if (cached_has_bits & 0x00000040u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_exercisequantity());
            }
            // optional bool override = 6;
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
           {
            // optional bool professionalCustomer = 9;
            if (cached_has_bits & 0x00000100u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ExerciseOptionsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ExerciseOptionsRequest*>(&to_msg);
  auto& from = static_cast<const ExerciseOptionsRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.ExerciseOptionsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_account(from._internal_account());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_manualordertime(from._internal_manualordertime());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_customeraccount(from._internal_customeraccount());
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.contract_ != nullptr);
      if (_this->_impl_.contract_ == nullptr) {
        _this->_impl_.contract_ =
            ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(arena, *from._impl_.contract_);
      } else {
        _this->_impl_.contract_->MergeFrom(*from._impl_.contract_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.orderid_ = from._impl_.orderid_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.exerciseaction_ = from._impl_.exerciseaction_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.exercisequantity_ = from._impl_.exercisequantity_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.override_ = from._impl_.override_;
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_impl_.professionalcustomer_ = from._impl_.professionalcustomer_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ExerciseOptionsRequest::CopyFrom(const ExerciseOptionsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.ExerciseOptionsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExerciseOptionsRequest::InternalSwap(ExerciseOptionsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_, &other->_impl_.account_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.manualordertime_, &other->_impl_.manualordertime_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.customeraccount_, &other->_impl_.customeraccount_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.professionalcustomer_)
      + sizeof(ExerciseOptionsRequest::_impl_.professionalcustomer_)
      - PROTOBUF_FIELD_OFFSET(ExerciseOptionsRequest, _impl_.contract_)>(
          reinterpret_cast<char*>(&_impl_.contract_),
          reinterpret_cast<char*>(&other->_impl_.contract_));
}

::google::protobuf::Metadata ExerciseOptionsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ExerciseOptionsRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
