// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FundamentalsData.proto
// Protobuf C++ Version: 5.29.5

#include "FundamentalsData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr FundamentalsData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reqid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FundamentalsData::FundamentalsData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FundamentalsDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FundamentalsDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FundamentalsDataDefaultTypeInternal() {}
  union {
    FundamentalsData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FundamentalsDataDefaultTypeInternal _FundamentalsData_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_FundamentalsData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_FundamentalsData_2eproto = nullptr;
const ::uint32_t
    TableStruct_FundamentalsData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::FundamentalsData, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::FundamentalsData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::FundamentalsData, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::FundamentalsData, _impl_.data_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::protobuf::FundamentalsData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_FundamentalsData_default_instance_._instance,
};
const char descriptor_table_protodef_FundamentalsData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026FundamentalsData.proto\022\010protobuf\"L\n\020Fu"
    "ndamentalsData\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022\021\n\004da"
    "ta\030\002 \001(\tH\001\210\001\001B\010\n\006_reqIdB\007\n\005_dataB@\n\026com."
    "ib.client.protobufB\025FundamentalsDataProt"
    "o\252\002\016IBApi.protobufb\006proto3"
};
static ::absl::once_flag descriptor_table_FundamentalsData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_FundamentalsData_2eproto = {
    false,
    false,
    186,
    descriptor_table_protodef_FundamentalsData_2eproto,
    "FundamentalsData.proto",
    &descriptor_table_FundamentalsData_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_FundamentalsData_2eproto::offsets,
    file_level_enum_descriptors_FundamentalsData_2eproto,
    file_level_service_descriptors_FundamentalsData_2eproto,
};
namespace protobuf {
// ===================================================================

class FundamentalsData::_Internal {
 public:
  using HasBits =
      decltype(std::declval<FundamentalsData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_._has_bits_);
};

FundamentalsData::FundamentalsData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.FundamentalsData)
}
inline PROTOBUF_NDEBUG_INLINE FundamentalsData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::FundamentalsData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_(arena, from.data_) {}

FundamentalsData::FundamentalsData(
    ::google::protobuf::Arena* arena,
    const FundamentalsData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FundamentalsData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.reqid_ = from._impl_.reqid_;

  // @@protoc_insertion_point(copy_constructor:protobuf.FundamentalsData)
}
inline PROTOBUF_NDEBUG_INLINE FundamentalsData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        data_(arena) {}

inline void FundamentalsData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reqid_ = {};
}
FundamentalsData::~FundamentalsData() {
  // @@protoc_insertion_point(destructor:protobuf.FundamentalsData)
  SharedDtor(*this);
}
inline void FundamentalsData::SharedDtor(MessageLite& self) {
  FundamentalsData& this_ = static_cast<FundamentalsData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FundamentalsData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FundamentalsData(arena);
}
constexpr auto FundamentalsData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FundamentalsData),
                                            alignof(FundamentalsData));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FundamentalsData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FundamentalsData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FundamentalsData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FundamentalsData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FundamentalsData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FundamentalsData>(), &FundamentalsData::ByteSizeLong,
            &FundamentalsData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_._cached_size_),
        false,
    },
    &FundamentalsData::kDescriptorMethods,
    &descriptor_table_FundamentalsData_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FundamentalsData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> FundamentalsData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::FundamentalsData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_.data_)}},
    // optional int32 reqId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FundamentalsData, _impl_.reqid_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_.reqid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 reqId = 1;
    {PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_.reqid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string data = 2;
    {PROTOBUF_FIELD_OFFSET(FundamentalsData, _impl_.data_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\4\0\0\0\0\0"
    "protobuf.FundamentalsData"
    "data"
  }},
};

PROTOBUF_NOINLINE void FundamentalsData::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.FundamentalsData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.data_.ClearNonDefaultToEmpty();
  }
  _impl_.reqid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FundamentalsData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FundamentalsData& this_ = static_cast<const FundamentalsData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FundamentalsData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FundamentalsData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.FundamentalsData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 reqId = 1;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_reqid(), target);
          }

          // optional string data = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_data();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.FundamentalsData.data");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.FundamentalsData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FundamentalsData::ByteSizeLong(const MessageLite& base) {
          const FundamentalsData& this_ = static_cast<const FundamentalsData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FundamentalsData::ByteSizeLong() const {
          const FundamentalsData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.FundamentalsData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional string data = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_data());
            }
            // optional int32 reqId = 1;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reqid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FundamentalsData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FundamentalsData*>(&to_msg);
  auto& from = static_cast<const FundamentalsData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.FundamentalsData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_data(from._internal_data());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.reqid_ = from._impl_.reqid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FundamentalsData::CopyFrom(const FundamentalsData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.FundamentalsData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FundamentalsData::InternalSwap(FundamentalsData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.reqid_, other->_impl_.reqid_);
}

::google::protobuf::Metadata FundamentalsData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_FundamentalsData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
