// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HistoricalSession.proto
// Protobuf C++ Version: 5.29.5

#ifndef HistoricalSession_2eproto_2epb_2eh
#define HistoricalSession_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_HistoricalSession_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_HistoricalSession_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_HistoricalSession_2eproto;
namespace protobuf {
class HistoricalSession;
struct HistoricalSessionDefaultTypeInternal;
extern HistoricalSessionDefaultTypeInternal _HistoricalSession_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class HistoricalSession final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.HistoricalSession) */ {
 public:
  inline HistoricalSession() : HistoricalSession(nullptr) {}
  ~HistoricalSession() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HistoricalSession* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HistoricalSession));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistoricalSession(
      ::google::protobuf::internal::ConstantInitialized);

  inline HistoricalSession(const HistoricalSession& from) : HistoricalSession(nullptr, from) {}
  inline HistoricalSession(HistoricalSession&& from) noexcept
      : HistoricalSession(nullptr, std::move(from)) {}
  inline HistoricalSession& operator=(const HistoricalSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline HistoricalSession& operator=(HistoricalSession&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HistoricalSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const HistoricalSession* internal_default_instance() {
    return reinterpret_cast<const HistoricalSession*>(
        &_HistoricalSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HistoricalSession& a, HistoricalSession& b) { a.Swap(&b); }
  inline void Swap(HistoricalSession* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HistoricalSession* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HistoricalSession* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HistoricalSession>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HistoricalSession& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HistoricalSession& from) { HistoricalSession::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HistoricalSession* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.HistoricalSession"; }

 protected:
  explicit HistoricalSession(::google::protobuf::Arena* arena);
  HistoricalSession(::google::protobuf::Arena* arena, const HistoricalSession& from);
  HistoricalSession(::google::protobuf::Arena* arena, HistoricalSession&& from) noexcept
      : HistoricalSession(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartDateTimeFieldNumber = 1,
    kEndDateTimeFieldNumber = 2,
    kRefDateFieldNumber = 3,
  };
  // optional string startDateTime = 1;
  bool has_startdatetime() const;
  void clear_startdatetime() ;
  const std::string& startdatetime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_startdatetime(Arg_&& arg, Args_... args);
  std::string* mutable_startdatetime();
  PROTOBUF_NODISCARD std::string* release_startdatetime();
  void set_allocated_startdatetime(std::string* value);

  private:
  const std::string& _internal_startdatetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_startdatetime(
      const std::string& value);
  std::string* _internal_mutable_startdatetime();

  public:
  // optional string endDateTime = 2;
  bool has_enddatetime() const;
  void clear_enddatetime() ;
  const std::string& enddatetime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_enddatetime(Arg_&& arg, Args_... args);
  std::string* mutable_enddatetime();
  PROTOBUF_NODISCARD std::string* release_enddatetime();
  void set_allocated_enddatetime(std::string* value);

  private:
  const std::string& _internal_enddatetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_enddatetime(
      const std::string& value);
  std::string* _internal_mutable_enddatetime();

  public:
  // optional string refDate = 3;
  bool has_refdate() const;
  void clear_refdate() ;
  const std::string& refdate() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_refdate(Arg_&& arg, Args_... args);
  std::string* mutable_refdate();
  PROTOBUF_NODISCARD std::string* release_refdate();
  void set_allocated_refdate(std::string* value);

  private:
  const std::string& _internal_refdate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_refdate(
      const std::string& value);
  std::string* _internal_mutable_refdate();

  public:
  // @@protoc_insertion_point(class_scope:protobuf.HistoricalSession)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      66, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HistoricalSession& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr startdatetime_;
    ::google::protobuf::internal::ArenaStringPtr enddatetime_;
    ::google::protobuf::internal::ArenaStringPtr refdate_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HistoricalSession_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HistoricalSession

// optional string startDateTime = 1;
inline bool HistoricalSession::has_startdatetime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void HistoricalSession::clear_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startdatetime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HistoricalSession::startdatetime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalSession.startDateTime)
  return _internal_startdatetime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalSession::set_startdatetime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.startdatetime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalSession.startDateTime)
}
inline std::string* HistoricalSession::mutable_startdatetime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_startdatetime();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalSession.startDateTime)
  return _s;
}
inline const std::string& HistoricalSession::_internal_startdatetime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.startdatetime_.Get();
}
inline void HistoricalSession::_internal_set_startdatetime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.startdatetime_.Set(value, GetArena());
}
inline std::string* HistoricalSession::_internal_mutable_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.startdatetime_.Mutable( GetArena());
}
inline std::string* HistoricalSession::release_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalSession.startDateTime)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.startdatetime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.startdatetime_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalSession::set_allocated_startdatetime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.startdatetime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.startdatetime_.IsDefault()) {
    _impl_.startdatetime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalSession.startDateTime)
}

// optional string endDateTime = 2;
inline bool HistoricalSession::has_enddatetime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void HistoricalSession::clear_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enddatetime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& HistoricalSession::enddatetime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalSession.endDateTime)
  return _internal_enddatetime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalSession::set_enddatetime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.enddatetime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalSession.endDateTime)
}
inline std::string* HistoricalSession::mutable_enddatetime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_enddatetime();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalSession.endDateTime)
  return _s;
}
inline const std::string& HistoricalSession::_internal_enddatetime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enddatetime_.Get();
}
inline void HistoricalSession::_internal_set_enddatetime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.enddatetime_.Set(value, GetArena());
}
inline std::string* HistoricalSession::_internal_mutable_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.enddatetime_.Mutable( GetArena());
}
inline std::string* HistoricalSession::release_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalSession.endDateTime)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.enddatetime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalSession::set_allocated_enddatetime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.enddatetime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.enddatetime_.IsDefault()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalSession.endDateTime)
}

// optional string refDate = 3;
inline bool HistoricalSession::has_refdate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void HistoricalSession::clear_refdate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.refdate_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& HistoricalSession::refdate() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalSession.refDate)
  return _internal_refdate();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalSession::set_refdate(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.refdate_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalSession.refDate)
}
inline std::string* HistoricalSession::mutable_refdate() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_refdate();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalSession.refDate)
  return _s;
}
inline const std::string& HistoricalSession::_internal_refdate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.refdate_.Get();
}
inline void HistoricalSession::_internal_set_refdate(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.refdate_.Set(value, GetArena());
}
inline std::string* HistoricalSession::_internal_mutable_refdate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.refdate_.Mutable( GetArena());
}
inline std::string* HistoricalSession::release_refdate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalSession.refDate)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.refdate_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.refdate_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalSession::set_allocated_refdate(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.refdate_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.refdate_.IsDefault()) {
    _impl_.refdate_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalSession.refDate)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // HistoricalSession_2eproto_2epb_2eh
