// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HistoricalNewsRequest.proto
// Protobuf C++ Version: 5.29.5

#ifndef HistoricalNewsRequest_2eproto_2epb_2eh
#define HistoricalNewsRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_HistoricalNewsRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_HistoricalNewsRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_HistoricalNewsRequest_2eproto;
namespace protobuf {
class HistoricalNewsRequest;
struct HistoricalNewsRequestDefaultTypeInternal;
extern HistoricalNewsRequestDefaultTypeInternal _HistoricalNewsRequest_default_instance_;
class HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse;
struct HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUseDefaultTypeInternal;
extern HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUseDefaultTypeInternal _HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse*>(
        &_HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_HistoricalNewsRequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      74, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class HistoricalNewsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.HistoricalNewsRequest) */ {
 public:
  inline HistoricalNewsRequest() : HistoricalNewsRequest(nullptr) {}
  ~HistoricalNewsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HistoricalNewsRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HistoricalNewsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistoricalNewsRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline HistoricalNewsRequest(const HistoricalNewsRequest& from) : HistoricalNewsRequest(nullptr, from) {}
  inline HistoricalNewsRequest(HistoricalNewsRequest&& from) noexcept
      : HistoricalNewsRequest(nullptr, std::move(from)) {}
  inline HistoricalNewsRequest& operator=(const HistoricalNewsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HistoricalNewsRequest& operator=(HistoricalNewsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HistoricalNewsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HistoricalNewsRequest* internal_default_instance() {
    return reinterpret_cast<const HistoricalNewsRequest*>(
        &_HistoricalNewsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HistoricalNewsRequest& a, HistoricalNewsRequest& b) { a.Swap(&b); }
  inline void Swap(HistoricalNewsRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HistoricalNewsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HistoricalNewsRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HistoricalNewsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HistoricalNewsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HistoricalNewsRequest& from) { HistoricalNewsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HistoricalNewsRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.HistoricalNewsRequest"; }

 protected:
  explicit HistoricalNewsRequest(::google::protobuf::Arena* arena);
  HistoricalNewsRequest(::google::protobuf::Arena* arena, const HistoricalNewsRequest& from);
  HistoricalNewsRequest(::google::protobuf::Arena* arena, HistoricalNewsRequest&& from) noexcept
      : HistoricalNewsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHistoricalNewsOptionsFieldNumber = 7,
    kProviderCodesFieldNumber = 3,
    kStartDateTimeFieldNumber = 4,
    kEndDateTimeFieldNumber = 5,
    kReqIdFieldNumber = 1,
    kConIdFieldNumber = 2,
    kTotalResultsFieldNumber = 6,
  };
  // map<string, string> historicalNewsOptions = 7;
  int historicalnewsoptions_size() const;
  private:
  int _internal_historicalnewsoptions_size() const;

  public:
  void clear_historicalnewsoptions() ;
  const ::google::protobuf::Map<std::string, std::string>& historicalnewsoptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_historicalnewsoptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_historicalnewsoptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_historicalnewsoptions();

  public:
  // optional string providerCodes = 3;
  bool has_providercodes() const;
  void clear_providercodes() ;
  const std::string& providercodes() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_providercodes(Arg_&& arg, Args_... args);
  std::string* mutable_providercodes();
  PROTOBUF_NODISCARD std::string* release_providercodes();
  void set_allocated_providercodes(std::string* value);

  private:
  const std::string& _internal_providercodes() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_providercodes(
      const std::string& value);
  std::string* _internal_mutable_providercodes();

  public:
  // optional string startDateTime = 4;
  bool has_startdatetime() const;
  void clear_startdatetime() ;
  const std::string& startdatetime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_startdatetime(Arg_&& arg, Args_... args);
  std::string* mutable_startdatetime();
  PROTOBUF_NODISCARD std::string* release_startdatetime();
  void set_allocated_startdatetime(std::string* value);

  private:
  const std::string& _internal_startdatetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_startdatetime(
      const std::string& value);
  std::string* _internal_mutable_startdatetime();

  public:
  // optional string endDateTime = 5;
  bool has_enddatetime() const;
  void clear_enddatetime() ;
  const std::string& enddatetime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_enddatetime(Arg_&& arg, Args_... args);
  std::string* mutable_enddatetime();
  PROTOBUF_NODISCARD std::string* release_enddatetime();
  void set_allocated_enddatetime(std::string* value);

  private:
  const std::string& _internal_enddatetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_enddatetime(
      const std::string& value);
  std::string* _internal_mutable_enddatetime();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // optional int32 conId = 2;
  bool has_conid() const;
  void clear_conid() ;
  ::int32_t conid() const;
  void set_conid(::int32_t value);

  private:
  ::int32_t _internal_conid() const;
  void _internal_set_conid(::int32_t value);

  public:
  // optional int32 totalResults = 6;
  bool has_totalresults() const;
  void clear_totalresults() ;
  ::int32_t totalresults() const;
  void set_totalresults(::int32_t value);

  private:
  ::int32_t _internal_totalresults() const;
  void _internal_set_totalresults(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.HistoricalNewsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 1,
      97, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HistoricalNewsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<HistoricalNewsRequest_HistoricalNewsOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        historicalnewsoptions_;
    ::google::protobuf::internal::ArenaStringPtr providercodes_;
    ::google::protobuf::internal::ArenaStringPtr startdatetime_;
    ::google::protobuf::internal::ArenaStringPtr enddatetime_;
    ::int32_t reqid_;
    ::int32_t conid_;
    ::int32_t totalresults_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HistoricalNewsRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HistoricalNewsRequest

// optional int32 reqId = 1;
inline bool HistoricalNewsRequest::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t HistoricalNewsRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.reqId)
  return _internal_reqid();
}
inline void HistoricalNewsRequest::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.reqId)
}
inline ::int32_t HistoricalNewsRequest::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void HistoricalNewsRequest::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional int32 conId = 2;
inline bool HistoricalNewsRequest::has_conid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_conid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t HistoricalNewsRequest::conid() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.conId)
  return _internal_conid();
}
inline void HistoricalNewsRequest::set_conid(::int32_t value) {
  _internal_set_conid(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.conId)
}
inline ::int32_t HistoricalNewsRequest::_internal_conid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conid_;
}
inline void HistoricalNewsRequest::_internal_set_conid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conid_ = value;
}

// optional string providerCodes = 3;
inline bool HistoricalNewsRequest::has_providercodes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_providercodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.providercodes_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HistoricalNewsRequest::providercodes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.providerCodes)
  return _internal_providercodes();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalNewsRequest::set_providercodes(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.providercodes_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.providerCodes)
}
inline std::string* HistoricalNewsRequest::mutable_providercodes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_providercodes();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalNewsRequest.providerCodes)
  return _s;
}
inline const std::string& HistoricalNewsRequest::_internal_providercodes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.providercodes_.Get();
}
inline void HistoricalNewsRequest::_internal_set_providercodes(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.providercodes_.Set(value, GetArena());
}
inline std::string* HistoricalNewsRequest::_internal_mutable_providercodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.providercodes_.Mutable( GetArena());
}
inline std::string* HistoricalNewsRequest::release_providercodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalNewsRequest.providerCodes)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.providercodes_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.providercodes_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalNewsRequest::set_allocated_providercodes(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.providercodes_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.providercodes_.IsDefault()) {
    _impl_.providercodes_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalNewsRequest.providerCodes)
}

// optional string startDateTime = 4;
inline bool HistoricalNewsRequest::has_startdatetime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startdatetime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& HistoricalNewsRequest::startdatetime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.startDateTime)
  return _internal_startdatetime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalNewsRequest::set_startdatetime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.startdatetime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.startDateTime)
}
inline std::string* HistoricalNewsRequest::mutable_startdatetime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_startdatetime();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalNewsRequest.startDateTime)
  return _s;
}
inline const std::string& HistoricalNewsRequest::_internal_startdatetime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.startdatetime_.Get();
}
inline void HistoricalNewsRequest::_internal_set_startdatetime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.startdatetime_.Set(value, GetArena());
}
inline std::string* HistoricalNewsRequest::_internal_mutable_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.startdatetime_.Mutable( GetArena());
}
inline std::string* HistoricalNewsRequest::release_startdatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalNewsRequest.startDateTime)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.startdatetime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.startdatetime_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalNewsRequest::set_allocated_startdatetime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.startdatetime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.startdatetime_.IsDefault()) {
    _impl_.startdatetime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalNewsRequest.startDateTime)
}

// optional string endDateTime = 5;
inline bool HistoricalNewsRequest::has_enddatetime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enddatetime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& HistoricalNewsRequest::enddatetime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.endDateTime)
  return _internal_enddatetime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalNewsRequest::set_enddatetime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.enddatetime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.endDateTime)
}
inline std::string* HistoricalNewsRequest::mutable_enddatetime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_enddatetime();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalNewsRequest.endDateTime)
  return _s;
}
inline const std::string& HistoricalNewsRequest::_internal_enddatetime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enddatetime_.Get();
}
inline void HistoricalNewsRequest::_internal_set_enddatetime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.enddatetime_.Set(value, GetArena());
}
inline std::string* HistoricalNewsRequest::_internal_mutable_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.enddatetime_.Mutable( GetArena());
}
inline std::string* HistoricalNewsRequest::release_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalNewsRequest.endDateTime)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.enddatetime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalNewsRequest::set_allocated_enddatetime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.enddatetime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.enddatetime_.IsDefault()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalNewsRequest.endDateTime)
}

// optional int32 totalResults = 6;
inline bool HistoricalNewsRequest::has_totalresults() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void HistoricalNewsRequest::clear_totalresults() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalresults_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t HistoricalNewsRequest::totalresults() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalNewsRequest.totalResults)
  return _internal_totalresults();
}
inline void HistoricalNewsRequest::set_totalresults(::int32_t value) {
  _internal_set_totalresults(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalNewsRequest.totalResults)
}
inline ::int32_t HistoricalNewsRequest::_internal_totalresults() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.totalresults_;
}
inline void HistoricalNewsRequest::_internal_set_totalresults(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.totalresults_ = value;
}

// map<string, string> historicalNewsOptions = 7;
inline int HistoricalNewsRequest::_internal_historicalnewsoptions_size() const {
  return _internal_historicalnewsoptions().size();
}
inline int HistoricalNewsRequest::historicalnewsoptions_size() const {
  return _internal_historicalnewsoptions_size();
}
inline void HistoricalNewsRequest::clear_historicalnewsoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.historicalnewsoptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& HistoricalNewsRequest::_internal_historicalnewsoptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.historicalnewsoptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& HistoricalNewsRequest::historicalnewsoptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.HistoricalNewsRequest.historicalNewsOptions)
  return _internal_historicalnewsoptions();
}
inline ::google::protobuf::Map<std::string, std::string>* HistoricalNewsRequest::_internal_mutable_historicalnewsoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.historicalnewsoptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* HistoricalNewsRequest::mutable_historicalnewsoptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.HistoricalNewsRequest.historicalNewsOptions)
  return _internal_mutable_historicalnewsoptions();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // HistoricalNewsRequest_2eproto_2epb_2eh
