// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: LockAndExitConfig.proto
// Protobuf C++ Version: 5.29.5

#ifndef LockAndExitConfig_2eproto_2epb_2eh
#define LockAndExitConfig_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_LockAndExitConfig_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_LockAndExitConfig_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_LockAndExitConfig_2eproto;
namespace protobuf {
class LockAndExitConfig;
struct LockAndExitConfigDefaultTypeInternal;
extern LockAndExitConfigDefaultTypeInternal _LockAndExitConfig_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class LockAndExitConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.LockAndExitConfig) */ {
 public:
  inline LockAndExitConfig() : LockAndExitConfig(nullptr) {}
  ~LockAndExitConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LockAndExitConfig* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LockAndExitConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LockAndExitConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline LockAndExitConfig(const LockAndExitConfig& from) : LockAndExitConfig(nullptr, from) {}
  inline LockAndExitConfig(LockAndExitConfig&& from) noexcept
      : LockAndExitConfig(nullptr, std::move(from)) {}
  inline LockAndExitConfig& operator=(const LockAndExitConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline LockAndExitConfig& operator=(LockAndExitConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LockAndExitConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const LockAndExitConfig* internal_default_instance() {
    return reinterpret_cast<const LockAndExitConfig*>(
        &_LockAndExitConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LockAndExitConfig& a, LockAndExitConfig& b) { a.Swap(&b); }
  inline void Swap(LockAndExitConfig* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LockAndExitConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LockAndExitConfig* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LockAndExitConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LockAndExitConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LockAndExitConfig& from) { LockAndExitConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LockAndExitConfig* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.LockAndExitConfig"; }

 protected:
  explicit LockAndExitConfig(::google::protobuf::Arena* arena);
  LockAndExitConfig(::google::protobuf::Arena* arena, const LockAndExitConfig& from);
  LockAndExitConfig(::google::protobuf::Arena* arena, LockAndExitConfig&& from) noexcept
      : LockAndExitConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAutoLogoffTimeFieldNumber = 1,
    kAutoLogoffPeriodFieldNumber = 2,
    kAutoLogoffTypeFieldNumber = 3,
  };
  // optional string autoLogoffTime = 1;
  bool has_autologofftime() const;
  void clear_autologofftime() ;
  const std::string& autologofftime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_autologofftime(Arg_&& arg, Args_... args);
  std::string* mutable_autologofftime();
  PROTOBUF_NODISCARD std::string* release_autologofftime();
  void set_allocated_autologofftime(std::string* value);

  private:
  const std::string& _internal_autologofftime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_autologofftime(
      const std::string& value);
  std::string* _internal_mutable_autologofftime();

  public:
  // optional string autoLogoffPeriod = 2;
  bool has_autologoffperiod() const;
  void clear_autologoffperiod() ;
  const std::string& autologoffperiod() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_autologoffperiod(Arg_&& arg, Args_... args);
  std::string* mutable_autologoffperiod();
  PROTOBUF_NODISCARD std::string* release_autologoffperiod();
  void set_allocated_autologoffperiod(std::string* value);

  private:
  const std::string& _internal_autologoffperiod() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_autologoffperiod(
      const std::string& value);
  std::string* _internal_mutable_autologoffperiod();

  public:
  // optional string autoLogoffType = 3;
  bool has_autologofftype() const;
  void clear_autologofftype() ;
  const std::string& autologofftype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_autologofftype(Arg_&& arg, Args_... args);
  std::string* mutable_autologofftype();
  PROTOBUF_NODISCARD std::string* release_autologofftype();
  void set_allocated_autologofftype(std::string* value);

  private:
  const std::string& _internal_autologofftype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_autologofftype(
      const std::string& value);
  std::string* _internal_mutable_autologofftype();

  public:
  // @@protoc_insertion_point(class_scope:protobuf.LockAndExitConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      79, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LockAndExitConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr autologofftime_;
    ::google::protobuf::internal::ArenaStringPtr autologoffperiod_;
    ::google::protobuf::internal::ArenaStringPtr autologofftype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_LockAndExitConfig_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LockAndExitConfig

// optional string autoLogoffTime = 1;
inline bool LockAndExitConfig::has_autologofftime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void LockAndExitConfig::clear_autologofftime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.autologofftime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LockAndExitConfig::autologofftime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffTime)
  return _internal_autologofftime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LockAndExitConfig::set_autologofftime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.autologofftime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffTime)
}
inline std::string* LockAndExitConfig::mutable_autologofftime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_autologofftime();
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffTime)
  return _s;
}
inline const std::string& LockAndExitConfig::_internal_autologofftime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.autologofftime_.Get();
}
inline void LockAndExitConfig::_internal_set_autologofftime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.autologofftime_.Set(value, GetArena());
}
inline std::string* LockAndExitConfig::_internal_mutable_autologofftime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.autologofftime_.Mutable( GetArena());
}
inline std::string* LockAndExitConfig::release_autologofftime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffTime)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.autologofftime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.autologofftime_.Set("", GetArena());
  }
  return released;
}
inline void LockAndExitConfig::set_allocated_autologofftime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.autologofftime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.autologofftime_.IsDefault()) {
    _impl_.autologofftime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffTime)
}

// optional string autoLogoffPeriod = 2;
inline bool LockAndExitConfig::has_autologoffperiod() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void LockAndExitConfig::clear_autologoffperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.autologoffperiod_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& LockAndExitConfig::autologoffperiod() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffPeriod)
  return _internal_autologoffperiod();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LockAndExitConfig::set_autologoffperiod(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.autologoffperiod_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffPeriod)
}
inline std::string* LockAndExitConfig::mutable_autologoffperiod() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_autologoffperiod();
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffPeriod)
  return _s;
}
inline const std::string& LockAndExitConfig::_internal_autologoffperiod() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.autologoffperiod_.Get();
}
inline void LockAndExitConfig::_internal_set_autologoffperiod(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.autologoffperiod_.Set(value, GetArena());
}
inline std::string* LockAndExitConfig::_internal_mutable_autologoffperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.autologoffperiod_.Mutable( GetArena());
}
inline std::string* LockAndExitConfig::release_autologoffperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffPeriod)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.autologoffperiod_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.autologoffperiod_.Set("", GetArena());
  }
  return released;
}
inline void LockAndExitConfig::set_allocated_autologoffperiod(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.autologoffperiod_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.autologoffperiod_.IsDefault()) {
    _impl_.autologoffperiod_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffPeriod)
}

// optional string autoLogoffType = 3;
inline bool LockAndExitConfig::has_autologofftype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void LockAndExitConfig::clear_autologofftype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.autologofftype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& LockAndExitConfig::autologofftype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.LockAndExitConfig.autoLogoffType)
  return _internal_autologofftype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LockAndExitConfig::set_autologofftype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.autologofftype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.LockAndExitConfig.autoLogoffType)
}
inline std::string* LockAndExitConfig::mutable_autologofftype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_autologofftype();
  // @@protoc_insertion_point(field_mutable:protobuf.LockAndExitConfig.autoLogoffType)
  return _s;
}
inline const std::string& LockAndExitConfig::_internal_autologofftype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.autologofftype_.Get();
}
inline void LockAndExitConfig::_internal_set_autologofftype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.autologofftype_.Set(value, GetArena());
}
inline std::string* LockAndExitConfig::_internal_mutable_autologofftype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.autologofftype_.Mutable( GetArena());
}
inline std::string* LockAndExitConfig::release_autologofftype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.LockAndExitConfig.autoLogoffType)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.autologofftype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.autologofftype_.Set("", GetArena());
  }
  return released;
}
inline void LockAndExitConfig::set_allocated_autologofftype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.autologofftype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.autologofftype_.IsDefault()) {
    _impl_.autologofftype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.LockAndExitConfig.autoLogoffType)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // LockAndExitConfig_2eproto_2epb_2eh
