// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NextValidId.proto
// Protobuf C++ Version: 5.29.5

#include "NextValidId.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr NextValidId::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        orderid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NextValidId::NextValidId(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NextValidIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NextValidIdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NextValidIdDefaultTypeInternal() {}
  union {
    NextValidId _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NextValidIdDefaultTypeInternal _NextValidId_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_NextValidId_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_NextValidId_2eproto = nullptr;
const ::uint32_t
    TableStruct_NextValidId_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::NextValidId, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::NextValidId, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::NextValidId, _impl_.orderid_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::protobuf::NextValidId)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_NextValidId_default_instance_._instance,
};
const char descriptor_table_protodef_NextValidId_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021NextValidId.proto\022\010protobuf\"/\n\013NextVal"
    "idId\022\024\n\007orderId\030\001 \001(\005H\000\210\001\001B\n\n\010_orderIdB;"
    "\n\026com.ib.client.protobufB\020NextValidIdPro"
    "to\252\002\016IBApi.protobufb\006proto3"
};
static ::absl::once_flag descriptor_table_NextValidId_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NextValidId_2eproto = {
    false,
    false,
    147,
    descriptor_table_protodef_NextValidId_2eproto,
    "NextValidId.proto",
    &descriptor_table_NextValidId_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_NextValidId_2eproto::offsets,
    file_level_enum_descriptors_NextValidId_2eproto,
    file_level_service_descriptors_NextValidId_2eproto,
};
namespace protobuf {
// ===================================================================

class NextValidId::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NextValidId>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NextValidId, _impl_._has_bits_);
};

NextValidId::NextValidId(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.NextValidId)
}
NextValidId::NextValidId(
    ::google::protobuf::Arena* arena, const NextValidId& from)
    : NextValidId(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NextValidId::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NextValidId::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.orderid_ = {};
}
NextValidId::~NextValidId() {
  // @@protoc_insertion_point(destructor:protobuf.NextValidId)
  SharedDtor(*this);
}
inline void NextValidId::SharedDtor(MessageLite& self) {
  NextValidId& this_ = static_cast<NextValidId&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* NextValidId::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NextValidId(arena);
}
constexpr auto NextValidId::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NextValidId),
                                            alignof(NextValidId));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NextValidId::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NextValidId_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NextValidId::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NextValidId>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NextValidId::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NextValidId>(), &NextValidId::ByteSizeLong,
            &NextValidId::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NextValidId, _impl_._cached_size_),
        false,
    },
    &NextValidId::kDescriptorMethods,
    &descriptor_table_NextValidId_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NextValidId::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> NextValidId::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NextValidId, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::NextValidId>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 orderId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NextValidId, _impl_.orderid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(NextValidId, _impl_.orderid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 orderId = 1;
    {PROTOBUF_FIELD_OFFSET(NextValidId, _impl_.orderid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void NextValidId::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.NextValidId)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.orderid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NextValidId::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NextValidId& this_ = static_cast<const NextValidId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NextValidId::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NextValidId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.NextValidId)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 orderId = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_orderid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.NextValidId)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NextValidId::ByteSizeLong(const MessageLite& base) {
          const NextValidId& this_ = static_cast<const NextValidId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NextValidId::ByteSizeLong() const {
          const NextValidId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.NextValidId)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // optional int32 orderId = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_orderid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NextValidId::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NextValidId*>(&to_msg);
  auto& from = static_cast<const NextValidId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.NextValidId)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.orderid_ = from._impl_.orderid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NextValidId::CopyFrom(const NextValidId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.NextValidId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NextValidId::InternalSwap(NextValidId* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        swap(_impl_.orderid_, other->_impl_.orderid_);
}

::google::protobuf::Metadata NextValidId::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_NextValidId_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
