// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ScannerSubscription.proto
// Protobuf C++ Version: 5.29.5

#ifndef ScannerSubscription_2eproto_2epb_2eh
#define ScannerSubscription_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ScannerSubscription_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ScannerSubscription_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ScannerSubscription_2eproto;
namespace protobuf {
class ScannerSubscription;
struct ScannerSubscriptionDefaultTypeInternal;
extern ScannerSubscriptionDefaultTypeInternal _ScannerSubscription_default_instance_;
class ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse;
struct ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUseDefaultTypeInternal;
extern ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUseDefaultTypeInternal _ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse_default_instance_;
class ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse;
struct ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUseDefaultTypeInternal;
extern ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUseDefaultTypeInternal _ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse*>(
        &_ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ScannerSubscription_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      77, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse*>(
        &_ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_ScannerSubscription_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      83, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class ScannerSubscription final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.ScannerSubscription) */ {
 public:
  inline ScannerSubscription() : ScannerSubscription(nullptr) {}
  ~ScannerSubscription() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScannerSubscription* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScannerSubscription));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScannerSubscription(
      ::google::protobuf::internal::ConstantInitialized);

  inline ScannerSubscription(const ScannerSubscription& from) : ScannerSubscription(nullptr, from) {}
  inline ScannerSubscription(ScannerSubscription&& from) noexcept
      : ScannerSubscription(nullptr, std::move(from)) {}
  inline ScannerSubscription& operator=(const ScannerSubscription& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScannerSubscription& operator=(ScannerSubscription&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScannerSubscription& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScannerSubscription* internal_default_instance() {
    return reinterpret_cast<const ScannerSubscription*>(
        &_ScannerSubscription_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ScannerSubscription& a, ScannerSubscription& b) { a.Swap(&b); }
  inline void Swap(ScannerSubscription* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScannerSubscription* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScannerSubscription* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScannerSubscription>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScannerSubscription& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScannerSubscription& from) { ScannerSubscription::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScannerSubscription* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.ScannerSubscription"; }

 protected:
  explicit ScannerSubscription(::google::protobuf::Arena* arena);
  ScannerSubscription(::google::protobuf::Arena* arena, const ScannerSubscription& from);
  ScannerSubscription(::google::protobuf::Arena* arena, ScannerSubscription&& from) noexcept
      : ScannerSubscription(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScannerSubscriptionFilterOptionsFieldNumber = 22,
    kScannerSubscriptionOptionsFieldNumber = 23,
    kInstrumentFieldNumber = 2,
    kLocationCodeFieldNumber = 3,
    kScanCodeFieldNumber = 4,
    kMoodyRatingAboveFieldNumber = 10,
    kMoodyRatingBelowFieldNumber = 11,
    kSpRatingAboveFieldNumber = 12,
    kSpRatingBelowFieldNumber = 13,
    kMaturityDateAboveFieldNumber = 14,
    kMaturityDateBelowFieldNumber = 15,
    kScannerSettingPairsFieldNumber = 20,
    kStockTypeFilterFieldNumber = 21,
    kAbovePriceFieldNumber = 5,
    kBelowPriceFieldNumber = 6,
    kAboveVolumeFieldNumber = 7,
    kMarketCapAboveFieldNumber = 8,
    kMarketCapBelowFieldNumber = 9,
    kNumberOfRowsFieldNumber = 1,
    kExcludeConvertibleFieldNumber = 18,
    kCouponRateAboveFieldNumber = 16,
    kCouponRateBelowFieldNumber = 17,
    kAverageOptionVolumeAboveFieldNumber = 19,
  };
  // map<string, string> scannerSubscriptionFilterOptions = 22;
  int scannersubscriptionfilteroptions_size() const;
  private:
  int _internal_scannersubscriptionfilteroptions_size() const;

  public:
  void clear_scannersubscriptionfilteroptions() ;
  const ::google::protobuf::Map<std::string, std::string>& scannersubscriptionfilteroptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_scannersubscriptionfilteroptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_scannersubscriptionfilteroptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_scannersubscriptionfilteroptions();

  public:
  // map<string, string> scannerSubscriptionOptions = 23;
  int scannersubscriptionoptions_size() const;
  private:
  int _internal_scannersubscriptionoptions_size() const;

  public:
  void clear_scannersubscriptionoptions() ;
  const ::google::protobuf::Map<std::string, std::string>& scannersubscriptionoptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_scannersubscriptionoptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_scannersubscriptionoptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_scannersubscriptionoptions();

  public:
  // optional string instrument = 2;
  bool has_instrument() const;
  void clear_instrument() ;
  const std::string& instrument() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_instrument(Arg_&& arg, Args_... args);
  std::string* mutable_instrument();
  PROTOBUF_NODISCARD std::string* release_instrument();
  void set_allocated_instrument(std::string* value);

  private:
  const std::string& _internal_instrument() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instrument(
      const std::string& value);
  std::string* _internal_mutable_instrument();

  public:
  // optional string locationCode = 3;
  bool has_locationcode() const;
  void clear_locationcode() ;
  const std::string& locationcode() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_locationcode(Arg_&& arg, Args_... args);
  std::string* mutable_locationcode();
  PROTOBUF_NODISCARD std::string* release_locationcode();
  void set_allocated_locationcode(std::string* value);

  private:
  const std::string& _internal_locationcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_locationcode(
      const std::string& value);
  std::string* _internal_mutable_locationcode();

  public:
  // optional string scanCode = 4;
  bool has_scancode() const;
  void clear_scancode() ;
  const std::string& scancode() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_scancode(Arg_&& arg, Args_... args);
  std::string* mutable_scancode();
  PROTOBUF_NODISCARD std::string* release_scancode();
  void set_allocated_scancode(std::string* value);

  private:
  const std::string& _internal_scancode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scancode(
      const std::string& value);
  std::string* _internal_mutable_scancode();

  public:
  // optional string moodyRatingAbove = 10;
  bool has_moodyratingabove() const;
  void clear_moodyratingabove() ;
  const std::string& moodyratingabove() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_moodyratingabove(Arg_&& arg, Args_... args);
  std::string* mutable_moodyratingabove();
  PROTOBUF_NODISCARD std::string* release_moodyratingabove();
  void set_allocated_moodyratingabove(std::string* value);

  private:
  const std::string& _internal_moodyratingabove() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_moodyratingabove(
      const std::string& value);
  std::string* _internal_mutable_moodyratingabove();

  public:
  // optional string moodyRatingBelow = 11;
  bool has_moodyratingbelow() const;
  void clear_moodyratingbelow() ;
  const std::string& moodyratingbelow() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_moodyratingbelow(Arg_&& arg, Args_... args);
  std::string* mutable_moodyratingbelow();
  PROTOBUF_NODISCARD std::string* release_moodyratingbelow();
  void set_allocated_moodyratingbelow(std::string* value);

  private:
  const std::string& _internal_moodyratingbelow() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_moodyratingbelow(
      const std::string& value);
  std::string* _internal_mutable_moodyratingbelow();

  public:
  // optional string spRatingAbove = 12;
  bool has_spratingabove() const;
  void clear_spratingabove() ;
  const std::string& spratingabove() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_spratingabove(Arg_&& arg, Args_... args);
  std::string* mutable_spratingabove();
  PROTOBUF_NODISCARD std::string* release_spratingabove();
  void set_allocated_spratingabove(std::string* value);

  private:
  const std::string& _internal_spratingabove() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_spratingabove(
      const std::string& value);
  std::string* _internal_mutable_spratingabove();

  public:
  // optional string spRatingBelow = 13;
  bool has_spratingbelow() const;
  void clear_spratingbelow() ;
  const std::string& spratingbelow() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_spratingbelow(Arg_&& arg, Args_... args);
  std::string* mutable_spratingbelow();
  PROTOBUF_NODISCARD std::string* release_spratingbelow();
  void set_allocated_spratingbelow(std::string* value);

  private:
  const std::string& _internal_spratingbelow() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_spratingbelow(
      const std::string& value);
  std::string* _internal_mutable_spratingbelow();

  public:
  // optional string maturityDateAbove = 14;
  bool has_maturitydateabove() const;
  void clear_maturitydateabove() ;
  const std::string& maturitydateabove() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_maturitydateabove(Arg_&& arg, Args_... args);
  std::string* mutable_maturitydateabove();
  PROTOBUF_NODISCARD std::string* release_maturitydateabove();
  void set_allocated_maturitydateabove(std::string* value);

  private:
  const std::string& _internal_maturitydateabove() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_maturitydateabove(
      const std::string& value);
  std::string* _internal_mutable_maturitydateabove();

  public:
  // optional string maturityDateBelow = 15;
  bool has_maturitydatebelow() const;
  void clear_maturitydatebelow() ;
  const std::string& maturitydatebelow() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_maturitydatebelow(Arg_&& arg, Args_... args);
  std::string* mutable_maturitydatebelow();
  PROTOBUF_NODISCARD std::string* release_maturitydatebelow();
  void set_allocated_maturitydatebelow(std::string* value);

  private:
  const std::string& _internal_maturitydatebelow() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_maturitydatebelow(
      const std::string& value);
  std::string* _internal_mutable_maturitydatebelow();

  public:
  // optional string scannerSettingPairs = 20;
  bool has_scannersettingpairs() const;
  void clear_scannersettingpairs() ;
  const std::string& scannersettingpairs() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_scannersettingpairs(Arg_&& arg, Args_... args);
  std::string* mutable_scannersettingpairs();
  PROTOBUF_NODISCARD std::string* release_scannersettingpairs();
  void set_allocated_scannersettingpairs(std::string* value);

  private:
  const std::string& _internal_scannersettingpairs() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_scannersettingpairs(
      const std::string& value);
  std::string* _internal_mutable_scannersettingpairs();

  public:
  // optional string stockTypeFilter = 21;
  bool has_stocktypefilter() const;
  void clear_stocktypefilter() ;
  const std::string& stocktypefilter() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_stocktypefilter(Arg_&& arg, Args_... args);
  std::string* mutable_stocktypefilter();
  PROTOBUF_NODISCARD std::string* release_stocktypefilter();
  void set_allocated_stocktypefilter(std::string* value);

  private:
  const std::string& _internal_stocktypefilter() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stocktypefilter(
      const std::string& value);
  std::string* _internal_mutable_stocktypefilter();

  public:
  // optional double abovePrice = 5;
  bool has_aboveprice() const;
  void clear_aboveprice() ;
  double aboveprice() const;
  void set_aboveprice(double value);

  private:
  double _internal_aboveprice() const;
  void _internal_set_aboveprice(double value);

  public:
  // optional double belowPrice = 6;
  bool has_belowprice() const;
  void clear_belowprice() ;
  double belowprice() const;
  void set_belowprice(double value);

  private:
  double _internal_belowprice() const;
  void _internal_set_belowprice(double value);

  public:
  // optional int64 aboveVolume = 7;
  bool has_abovevolume() const;
  void clear_abovevolume() ;
  ::int64_t abovevolume() const;
  void set_abovevolume(::int64_t value);

  private:
  ::int64_t _internal_abovevolume() const;
  void _internal_set_abovevolume(::int64_t value);

  public:
  // optional double marketCapAbove = 8;
  bool has_marketcapabove() const;
  void clear_marketcapabove() ;
  double marketcapabove() const;
  void set_marketcapabove(double value);

  private:
  double _internal_marketcapabove() const;
  void _internal_set_marketcapabove(double value);

  public:
  // optional double marketCapBelow = 9;
  bool has_marketcapbelow() const;
  void clear_marketcapbelow() ;
  double marketcapbelow() const;
  void set_marketcapbelow(double value);

  private:
  double _internal_marketcapbelow() const;
  void _internal_set_marketcapbelow(double value);

  public:
  // optional int32 numberOfRows = 1;
  bool has_numberofrows() const;
  void clear_numberofrows() ;
  ::int32_t numberofrows() const;
  void set_numberofrows(::int32_t value);

  private:
  ::int32_t _internal_numberofrows() const;
  void _internal_set_numberofrows(::int32_t value);

  public:
  // optional bool excludeConvertible = 18;
  bool has_excludeconvertible() const;
  void clear_excludeconvertible() ;
  bool excludeconvertible() const;
  void set_excludeconvertible(bool value);

  private:
  bool _internal_excludeconvertible() const;
  void _internal_set_excludeconvertible(bool value);

  public:
  // optional double couponRateAbove = 16;
  bool has_couponrateabove() const;
  void clear_couponrateabove() ;
  double couponrateabove() const;
  void set_couponrateabove(double value);

  private:
  double _internal_couponrateabove() const;
  void _internal_set_couponrateabove(double value);

  public:
  // optional double couponRateBelow = 17;
  bool has_couponratebelow() const;
  void clear_couponratebelow() ;
  double couponratebelow() const;
  void set_couponratebelow(double value);

  private:
  double _internal_couponratebelow() const;
  void _internal_set_couponratebelow(double value);

  public:
  // optional int64 averageOptionVolumeAbove = 19;
  bool has_averageoptionvolumeabove() const;
  void clear_averageoptionvolumeabove() ;
  ::int64_t averageoptionvolumeabove() const;
  void set_averageoptionvolumeabove(::int64_t value);

  private:
  ::int64_t _internal_averageoptionvolumeabove() const;
  void _internal_set_averageoptionvolumeabove(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.ScannerSubscription)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      5, 23, 2,
      267, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ScannerSubscription& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<ScannerSubscription_ScannerSubscriptionFilterOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        scannersubscriptionfilteroptions_;
    ::google::protobuf::internal::MapField<ScannerSubscription_ScannerSubscriptionOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        scannersubscriptionoptions_;
    ::google::protobuf::internal::ArenaStringPtr instrument_;
    ::google::protobuf::internal::ArenaStringPtr locationcode_;
    ::google::protobuf::internal::ArenaStringPtr scancode_;
    ::google::protobuf::internal::ArenaStringPtr moodyratingabove_;
    ::google::protobuf::internal::ArenaStringPtr moodyratingbelow_;
    ::google::protobuf::internal::ArenaStringPtr spratingabove_;
    ::google::protobuf::internal::ArenaStringPtr spratingbelow_;
    ::google::protobuf::internal::ArenaStringPtr maturitydateabove_;
    ::google::protobuf::internal::ArenaStringPtr maturitydatebelow_;
    ::google::protobuf::internal::ArenaStringPtr scannersettingpairs_;
    ::google::protobuf::internal::ArenaStringPtr stocktypefilter_;
    double aboveprice_;
    double belowprice_;
    ::int64_t abovevolume_;
    double marketcapabove_;
    double marketcapbelow_;
    ::int32_t numberofrows_;
    bool excludeconvertible_;
    double couponrateabove_;
    double couponratebelow_;
    ::int64_t averageoptionvolumeabove_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ScannerSubscription_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ScannerSubscription

// optional int32 numberOfRows = 1;
inline bool ScannerSubscription::has_numberofrows() const {
  bool value = (_impl_._has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_numberofrows() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numberofrows_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline ::int32_t ScannerSubscription::numberofrows() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.numberOfRows)
  return _internal_numberofrows();
}
inline void ScannerSubscription::set_numberofrows(::int32_t value) {
  _internal_set_numberofrows(value);
  _impl_._has_bits_[0] |= 0x00010000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.numberOfRows)
}
inline ::int32_t ScannerSubscription::_internal_numberofrows() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numberofrows_;
}
inline void ScannerSubscription::_internal_set_numberofrows(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numberofrows_ = value;
}

// optional string instrument = 2;
inline bool ScannerSubscription::has_instrument() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ScannerSubscription::clear_instrument() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.instrument_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ScannerSubscription::instrument() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.instrument)
  return _internal_instrument();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_instrument(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.instrument_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.instrument)
}
inline std::string* ScannerSubscription::mutable_instrument() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_instrument();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.instrument)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_instrument() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.instrument_.Get();
}
inline void ScannerSubscription::_internal_set_instrument(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.instrument_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_instrument() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.instrument_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_instrument() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.instrument)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.instrument_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.instrument_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_instrument(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.instrument_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.instrument_.IsDefault()) {
    _impl_.instrument_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.instrument)
}

// optional string locationCode = 3;
inline bool ScannerSubscription::has_locationcode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ScannerSubscription::clear_locationcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.locationcode_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ScannerSubscription::locationcode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.locationCode)
  return _internal_locationcode();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_locationcode(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.locationcode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.locationCode)
}
inline std::string* ScannerSubscription::mutable_locationcode() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_locationcode();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.locationCode)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_locationcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.locationcode_.Get();
}
inline void ScannerSubscription::_internal_set_locationcode(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.locationcode_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_locationcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.locationcode_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_locationcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.locationCode)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.locationcode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.locationcode_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_locationcode(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.locationcode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.locationcode_.IsDefault()) {
    _impl_.locationcode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.locationCode)
}

// optional string scanCode = 4;
inline bool ScannerSubscription::has_scancode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ScannerSubscription::clear_scancode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scancode_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ScannerSubscription::scancode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.scanCode)
  return _internal_scancode();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_scancode(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.scancode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.scanCode)
}
inline std::string* ScannerSubscription::mutable_scancode() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_scancode();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.scanCode)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_scancode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scancode_.Get();
}
inline void ScannerSubscription::_internal_set_scancode(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.scancode_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_scancode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.scancode_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_scancode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.scanCode)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.scancode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.scancode_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_scancode(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.scancode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.scancode_.IsDefault()) {
    _impl_.scancode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.scanCode)
}

// optional double abovePrice = 5;
inline bool ScannerSubscription::has_aboveprice() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void ScannerSubscription::clear_aboveprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aboveprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline double ScannerSubscription::aboveprice() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.abovePrice)
  return _internal_aboveprice();
}
inline void ScannerSubscription::set_aboveprice(double value) {
  _internal_set_aboveprice(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.abovePrice)
}
inline double ScannerSubscription::_internal_aboveprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.aboveprice_;
}
inline void ScannerSubscription::_internal_set_aboveprice(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aboveprice_ = value;
}

// optional double belowPrice = 6;
inline bool ScannerSubscription::has_belowprice() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_belowprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.belowprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline double ScannerSubscription::belowprice() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.belowPrice)
  return _internal_belowprice();
}
inline void ScannerSubscription::set_belowprice(double value) {
  _internal_set_belowprice(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.belowPrice)
}
inline double ScannerSubscription::_internal_belowprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.belowprice_;
}
inline void ScannerSubscription::_internal_set_belowprice(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.belowprice_ = value;
}

// optional int64 aboveVolume = 7;
inline bool ScannerSubscription::has_abovevolume() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_abovevolume() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abovevolume_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline ::int64_t ScannerSubscription::abovevolume() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.aboveVolume)
  return _internal_abovevolume();
}
inline void ScannerSubscription::set_abovevolume(::int64_t value) {
  _internal_set_abovevolume(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.aboveVolume)
}
inline ::int64_t ScannerSubscription::_internal_abovevolume() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.abovevolume_;
}
inline void ScannerSubscription::_internal_set_abovevolume(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abovevolume_ = value;
}

// optional double marketCapAbove = 8;
inline bool ScannerSubscription::has_marketcapabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_marketcapabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.marketcapabove_ = 0;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline double ScannerSubscription::marketcapabove() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.marketCapAbove)
  return _internal_marketcapabove();
}
inline void ScannerSubscription::set_marketcapabove(double value) {
  _internal_set_marketcapabove(value);
  _impl_._has_bits_[0] |= 0x00004000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.marketCapAbove)
}
inline double ScannerSubscription::_internal_marketcapabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.marketcapabove_;
}
inline void ScannerSubscription::_internal_set_marketcapabove(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.marketcapabove_ = value;
}

// optional double marketCapBelow = 9;
inline bool ScannerSubscription::has_marketcapbelow() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_marketcapbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.marketcapbelow_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline double ScannerSubscription::marketcapbelow() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.marketCapBelow)
  return _internal_marketcapbelow();
}
inline void ScannerSubscription::set_marketcapbelow(double value) {
  _internal_set_marketcapbelow(value);
  _impl_._has_bits_[0] |= 0x00008000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.marketCapBelow)
}
inline double ScannerSubscription::_internal_marketcapbelow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.marketcapbelow_;
}
inline void ScannerSubscription::_internal_set_marketcapbelow(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.marketcapbelow_ = value;
}

// optional string moodyRatingAbove = 10;
inline bool ScannerSubscription::has_moodyratingabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ScannerSubscription::clear_moodyratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.moodyratingabove_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ScannerSubscription::moodyratingabove() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.moodyRatingAbove)
  return _internal_moodyratingabove();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_moodyratingabove(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.moodyratingabove_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.moodyRatingAbove)
}
inline std::string* ScannerSubscription::mutable_moodyratingabove() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_moodyratingabove();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.moodyRatingAbove)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_moodyratingabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.moodyratingabove_.Get();
}
inline void ScannerSubscription::_internal_set_moodyratingabove(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.moodyratingabove_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_moodyratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.moodyratingabove_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_moodyratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.moodyRatingAbove)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.moodyratingabove_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.moodyratingabove_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_moodyratingabove(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.moodyratingabove_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.moodyratingabove_.IsDefault()) {
    _impl_.moodyratingabove_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.moodyRatingAbove)
}

// optional string moodyRatingBelow = 11;
inline bool ScannerSubscription::has_moodyratingbelow() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ScannerSubscription::clear_moodyratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.moodyratingbelow_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ScannerSubscription::moodyratingbelow() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.moodyRatingBelow)
  return _internal_moodyratingbelow();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_moodyratingbelow(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.moodyratingbelow_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.moodyRatingBelow)
}
inline std::string* ScannerSubscription::mutable_moodyratingbelow() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_moodyratingbelow();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.moodyRatingBelow)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_moodyratingbelow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.moodyratingbelow_.Get();
}
inline void ScannerSubscription::_internal_set_moodyratingbelow(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.moodyratingbelow_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_moodyratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.moodyratingbelow_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_moodyratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.moodyRatingBelow)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.moodyratingbelow_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.moodyratingbelow_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_moodyratingbelow(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.moodyratingbelow_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.moodyratingbelow_.IsDefault()) {
    _impl_.moodyratingbelow_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.moodyRatingBelow)
}

// optional string spRatingAbove = 12;
inline bool ScannerSubscription::has_spratingabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ScannerSubscription::clear_spratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spratingabove_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ScannerSubscription::spratingabove() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.spRatingAbove)
  return _internal_spratingabove();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_spratingabove(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.spratingabove_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.spRatingAbove)
}
inline std::string* ScannerSubscription::mutable_spratingabove() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_spratingabove();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.spRatingAbove)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_spratingabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spratingabove_.Get();
}
inline void ScannerSubscription::_internal_set_spratingabove(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.spratingabove_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_spratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.spratingabove_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_spratingabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.spRatingAbove)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.spratingabove_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.spratingabove_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_spratingabove(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.spratingabove_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.spratingabove_.IsDefault()) {
    _impl_.spratingabove_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.spRatingAbove)
}

// optional string spRatingBelow = 13;
inline bool ScannerSubscription::has_spratingbelow() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ScannerSubscription::clear_spratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spratingbelow_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& ScannerSubscription::spratingbelow() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.spRatingBelow)
  return _internal_spratingbelow();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_spratingbelow(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.spratingbelow_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.spRatingBelow)
}
inline std::string* ScannerSubscription::mutable_spratingbelow() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_spratingbelow();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.spRatingBelow)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_spratingbelow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spratingbelow_.Get();
}
inline void ScannerSubscription::_internal_set_spratingbelow(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.spratingbelow_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_spratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.spratingbelow_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_spratingbelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.spRatingBelow)
  if ((_impl_._has_bits_[0] & 0x00000040u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* released = _impl_.spratingbelow_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.spratingbelow_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_spratingbelow(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.spratingbelow_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.spratingbelow_.IsDefault()) {
    _impl_.spratingbelow_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.spRatingBelow)
}

// optional string maturityDateAbove = 14;
inline bool ScannerSubscription::has_maturitydateabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void ScannerSubscription::clear_maturitydateabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maturitydateabove_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& ScannerSubscription::maturitydateabove() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.maturityDateAbove)
  return _internal_maturitydateabove();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_maturitydateabove(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.maturitydateabove_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.maturityDateAbove)
}
inline std::string* ScannerSubscription::mutable_maturitydateabove() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_maturitydateabove();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.maturityDateAbove)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_maturitydateabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maturitydateabove_.Get();
}
inline void ScannerSubscription::_internal_set_maturitydateabove(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.maturitydateabove_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_maturitydateabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.maturitydateabove_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_maturitydateabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.maturityDateAbove)
  if ((_impl_._has_bits_[0] & 0x00000080u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* released = _impl_.maturitydateabove_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.maturitydateabove_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_maturitydateabove(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.maturitydateabove_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.maturitydateabove_.IsDefault()) {
    _impl_.maturitydateabove_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.maturityDateAbove)
}

// optional string maturityDateBelow = 15;
inline bool ScannerSubscription::has_maturitydatebelow() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void ScannerSubscription::clear_maturitydatebelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.maturitydatebelow_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& ScannerSubscription::maturitydatebelow() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.maturityDateBelow)
  return _internal_maturitydatebelow();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_maturitydatebelow(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.maturitydatebelow_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.maturityDateBelow)
}
inline std::string* ScannerSubscription::mutable_maturitydatebelow() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_maturitydatebelow();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.maturityDateBelow)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_maturitydatebelow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.maturitydatebelow_.Get();
}
inline void ScannerSubscription::_internal_set_maturitydatebelow(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.maturitydatebelow_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_maturitydatebelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.maturitydatebelow_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_maturitydatebelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.maturityDateBelow)
  if ((_impl_._has_bits_[0] & 0x00000100u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* released = _impl_.maturitydatebelow_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.maturitydatebelow_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_maturitydatebelow(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.maturitydatebelow_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.maturitydatebelow_.IsDefault()) {
    _impl_.maturitydatebelow_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.maturityDateBelow)
}

// optional double couponRateAbove = 16;
inline bool ScannerSubscription::has_couponrateabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_couponrateabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.couponrateabove_ = 0;
  _impl_._has_bits_[0] &= ~0x00040000u;
}
inline double ScannerSubscription::couponrateabove() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.couponRateAbove)
  return _internal_couponrateabove();
}
inline void ScannerSubscription::set_couponrateabove(double value) {
  _internal_set_couponrateabove(value);
  _impl_._has_bits_[0] |= 0x00040000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.couponRateAbove)
}
inline double ScannerSubscription::_internal_couponrateabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.couponrateabove_;
}
inline void ScannerSubscription::_internal_set_couponrateabove(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.couponrateabove_ = value;
}

// optional double couponRateBelow = 17;
inline bool ScannerSubscription::has_couponratebelow() const {
  bool value = (_impl_._has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_couponratebelow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.couponratebelow_ = 0;
  _impl_._has_bits_[0] &= ~0x00080000u;
}
inline double ScannerSubscription::couponratebelow() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.couponRateBelow)
  return _internal_couponratebelow();
}
inline void ScannerSubscription::set_couponratebelow(double value) {
  _internal_set_couponratebelow(value);
  _impl_._has_bits_[0] |= 0x00080000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.couponRateBelow)
}
inline double ScannerSubscription::_internal_couponratebelow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.couponratebelow_;
}
inline void ScannerSubscription::_internal_set_couponratebelow(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.couponratebelow_ = value;
}

// optional bool excludeConvertible = 18;
inline bool ScannerSubscription::has_excludeconvertible() const {
  bool value = (_impl_._has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_excludeconvertible() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.excludeconvertible_ = false;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline bool ScannerSubscription::excludeconvertible() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.excludeConvertible)
  return _internal_excludeconvertible();
}
inline void ScannerSubscription::set_excludeconvertible(bool value) {
  _internal_set_excludeconvertible(value);
  _impl_._has_bits_[0] |= 0x00020000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.excludeConvertible)
}
inline bool ScannerSubscription::_internal_excludeconvertible() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.excludeconvertible_;
}
inline void ScannerSubscription::_internal_set_excludeconvertible(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.excludeconvertible_ = value;
}

// optional int64 averageOptionVolumeAbove = 19;
inline bool ScannerSubscription::has_averageoptionvolumeabove() const {
  bool value = (_impl_._has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline void ScannerSubscription::clear_averageoptionvolumeabove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.averageoptionvolumeabove_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00100000u;
}
inline ::int64_t ScannerSubscription::averageoptionvolumeabove() const {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.averageOptionVolumeAbove)
  return _internal_averageoptionvolumeabove();
}
inline void ScannerSubscription::set_averageoptionvolumeabove(::int64_t value) {
  _internal_set_averageoptionvolumeabove(value);
  _impl_._has_bits_[0] |= 0x00100000u;
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.averageOptionVolumeAbove)
}
inline ::int64_t ScannerSubscription::_internal_averageoptionvolumeabove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.averageoptionvolumeabove_;
}
inline void ScannerSubscription::_internal_set_averageoptionvolumeabove(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.averageoptionvolumeabove_ = value;
}

// optional string scannerSettingPairs = 20;
inline bool ScannerSubscription::has_scannersettingpairs() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void ScannerSubscription::clear_scannersettingpairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scannersettingpairs_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline const std::string& ScannerSubscription::scannersettingpairs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.scannerSettingPairs)
  return _internal_scannersettingpairs();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_scannersettingpairs(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.scannersettingpairs_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.scannerSettingPairs)
}
inline std::string* ScannerSubscription::mutable_scannersettingpairs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_scannersettingpairs();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.scannerSettingPairs)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_scannersettingpairs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scannersettingpairs_.Get();
}
inline void ScannerSubscription::_internal_set_scannersettingpairs(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.scannersettingpairs_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_scannersettingpairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000200u;
  return _impl_.scannersettingpairs_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_scannersettingpairs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.scannerSettingPairs)
  if ((_impl_._has_bits_[0] & 0x00000200u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000200u;
  auto* released = _impl_.scannersettingpairs_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.scannersettingpairs_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_scannersettingpairs(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  _impl_.scannersettingpairs_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.scannersettingpairs_.IsDefault()) {
    _impl_.scannersettingpairs_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.scannerSettingPairs)
}

// optional string stockTypeFilter = 21;
inline bool ScannerSubscription::has_stocktypefilter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void ScannerSubscription::clear_stocktypefilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stocktypefilter_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline const std::string& ScannerSubscription::stocktypefilter() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ScannerSubscription.stockTypeFilter)
  return _internal_stocktypefilter();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ScannerSubscription::set_stocktypefilter(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.stocktypefilter_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.ScannerSubscription.stockTypeFilter)
}
inline std::string* ScannerSubscription::mutable_stocktypefilter() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_stocktypefilter();
  // @@protoc_insertion_point(field_mutable:protobuf.ScannerSubscription.stockTypeFilter)
  return _s;
}
inline const std::string& ScannerSubscription::_internal_stocktypefilter() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stocktypefilter_.Get();
}
inline void ScannerSubscription::_internal_set_stocktypefilter(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.stocktypefilter_.Set(value, GetArena());
}
inline std::string* ScannerSubscription::_internal_mutable_stocktypefilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000400u;
  return _impl_.stocktypefilter_.Mutable( GetArena());
}
inline std::string* ScannerSubscription::release_stocktypefilter() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ScannerSubscription.stockTypeFilter)
  if ((_impl_._has_bits_[0] & 0x00000400u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000400u;
  auto* released = _impl_.stocktypefilter_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.stocktypefilter_.Set("", GetArena());
  }
  return released;
}
inline void ScannerSubscription::set_allocated_stocktypefilter(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  _impl_.stocktypefilter_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.stocktypefilter_.IsDefault()) {
    _impl_.stocktypefilter_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.ScannerSubscription.stockTypeFilter)
}

// map<string, string> scannerSubscriptionFilterOptions = 22;
inline int ScannerSubscription::_internal_scannersubscriptionfilteroptions_size() const {
  return _internal_scannersubscriptionfilteroptions().size();
}
inline int ScannerSubscription::scannersubscriptionfilteroptions_size() const {
  return _internal_scannersubscriptionfilteroptions_size();
}
inline void ScannerSubscription::clear_scannersubscriptionfilteroptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scannersubscriptionfilteroptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& ScannerSubscription::_internal_scannersubscriptionfilteroptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scannersubscriptionfilteroptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& ScannerSubscription::scannersubscriptionfilteroptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.ScannerSubscription.scannerSubscriptionFilterOptions)
  return _internal_scannersubscriptionfilteroptions();
}
inline ::google::protobuf::Map<std::string, std::string>* ScannerSubscription::_internal_mutable_scannersubscriptionfilteroptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.scannersubscriptionfilteroptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* ScannerSubscription::mutable_scannersubscriptionfilteroptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.ScannerSubscription.scannerSubscriptionFilterOptions)
  return _internal_mutable_scannersubscriptionfilteroptions();
}

// map<string, string> scannerSubscriptionOptions = 23;
inline int ScannerSubscription::_internal_scannersubscriptionoptions_size() const {
  return _internal_scannersubscriptionoptions().size();
}
inline int ScannerSubscription::scannersubscriptionoptions_size() const {
  return _internal_scannersubscriptionoptions_size();
}
inline void ScannerSubscription::clear_scannersubscriptionoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scannersubscriptionoptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& ScannerSubscription::_internal_scannersubscriptionoptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scannersubscriptionoptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& ScannerSubscription::scannersubscriptionoptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.ScannerSubscription.scannerSubscriptionOptions)
  return _internal_scannersubscriptionoptions();
}
inline ::google::protobuf::Map<std::string, std::string>* ScannerSubscription::_internal_mutable_scannersubscriptionoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.scannersubscriptionoptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* ScannerSubscription::mutable_scannersubscriptionoptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.ScannerSubscription.scannerSubscriptionOptions)
  return _internal_mutable_scannersubscriptionoptions();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ScannerSubscription_2eproto_2epb_2eh
