// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SmartComponent.proto
// Protobuf C++ Version: 5.29.5

#include "SmartComponent.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr SmartComponent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        exchange_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        exchangeletter_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bitnumber_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SmartComponent::SmartComponent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SmartComponentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SmartComponentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SmartComponentDefaultTypeInternal() {}
  union {
    SmartComponent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SmartComponentDefaultTypeInternal _SmartComponent_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SmartComponent_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SmartComponent_2eproto = nullptr;
const ::uint32_t
    TableStruct_SmartComponent_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::SmartComponent, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::SmartComponent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::SmartComponent, _impl_.bitnumber_),
        PROTOBUF_FIELD_OFFSET(::protobuf::SmartComponent, _impl_.exchange_),
        PROTOBUF_FIELD_OFFSET(::protobuf::SmartComponent, _impl_.exchangeletter_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::protobuf::SmartComponent)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_SmartComponent_default_instance_._instance,
};
const char descriptor_table_protodef_SmartComponent_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024SmartComponent.proto\022\010protobuf\"\212\001\n\016Sma"
    "rtComponent\022\026\n\tbitNumber\030\001 \001(\005H\000\210\001\001\022\025\n\010e"
    "xchange\030\002 \001(\tH\001\210\001\001\022\033\n\016exchangeLetter\030\003 \001"
    "(\tH\002\210\001\001B\014\n\n_bitNumberB\013\n\t_exchangeB\021\n\017_e"
    "xchangeLetterB>\n\026com.ib.client.protobufB"
    "\023SmartComponentProto\252\002\016IBApi.protobufb\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_SmartComponent_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SmartComponent_2eproto = {
    false,
    false,
    245,
    descriptor_table_protodef_SmartComponent_2eproto,
    "SmartComponent.proto",
    &descriptor_table_SmartComponent_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SmartComponent_2eproto::offsets,
    file_level_enum_descriptors_SmartComponent_2eproto,
    file_level_service_descriptors_SmartComponent_2eproto,
};
namespace protobuf {
// ===================================================================

class SmartComponent::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SmartComponent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_._has_bits_);
};

SmartComponent::SmartComponent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.SmartComponent)
}
inline PROTOBUF_NDEBUG_INLINE SmartComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::SmartComponent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        exchange_(arena, from.exchange_),
        exchangeletter_(arena, from.exchangeletter_) {}

SmartComponent::SmartComponent(
    ::google::protobuf::Arena* arena,
    const SmartComponent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SmartComponent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.bitnumber_ = from._impl_.bitnumber_;

  // @@protoc_insertion_point(copy_constructor:protobuf.SmartComponent)
}
inline PROTOBUF_NDEBUG_INLINE SmartComponent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        exchange_(arena),
        exchangeletter_(arena) {}

inline void SmartComponent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.bitnumber_ = {};
}
SmartComponent::~SmartComponent() {
  // @@protoc_insertion_point(destructor:protobuf.SmartComponent)
  SharedDtor(*this);
}
inline void SmartComponent::SharedDtor(MessageLite& self) {
  SmartComponent& this_ = static_cast<SmartComponent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.exchange_.Destroy();
  this_._impl_.exchangeletter_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SmartComponent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SmartComponent(arena);
}
constexpr auto SmartComponent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SmartComponent),
                                            alignof(SmartComponent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SmartComponent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SmartComponent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SmartComponent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SmartComponent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SmartComponent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SmartComponent>(), &SmartComponent::ByteSizeLong,
            &SmartComponent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_._cached_size_),
        false,
    },
    &SmartComponent::kDescriptorMethods,
    &descriptor_table_SmartComponent_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SmartComponent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 54, 2> SmartComponent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::SmartComponent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 bitNumber = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SmartComponent, _impl_.bitnumber_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.bitnumber_)}},
    // optional string exchange = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.exchange_)}},
    // optional string exchangeLetter = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.exchangeletter_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 bitNumber = 1;
    {PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.bitnumber_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string exchange = 2;
    {PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.exchange_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string exchangeLetter = 3;
    {PROTOBUF_FIELD_OFFSET(SmartComponent, _impl_.exchangeletter_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\10\16\0\0\0\0"
    "protobuf.SmartComponent"
    "exchange"
    "exchangeLetter"
  }},
};

PROTOBUF_NOINLINE void SmartComponent::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.SmartComponent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.exchange_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.exchangeletter_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.bitnumber_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SmartComponent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SmartComponent& this_ = static_cast<const SmartComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SmartComponent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SmartComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.SmartComponent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 bitNumber = 1;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_bitnumber(), target);
          }

          // optional string exchange = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_exchange();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.SmartComponent.exchange");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional string exchangeLetter = 3;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_exchangeletter();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.SmartComponent.exchangeLetter");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.SmartComponent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SmartComponent::ByteSizeLong(const MessageLite& base) {
          const SmartComponent& this_ = static_cast<const SmartComponent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SmartComponent::ByteSizeLong() const {
          const SmartComponent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.SmartComponent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional string exchange = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_exchange());
            }
            // optional string exchangeLetter = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_exchangeletter());
            }
            // optional int32 bitNumber = 1;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_bitnumber());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SmartComponent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SmartComponent*>(&to_msg);
  auto& from = static_cast<const SmartComponent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.SmartComponent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_exchange(from._internal_exchange());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_exchangeletter(from._internal_exchangeletter());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.bitnumber_ = from._impl_.bitnumber_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SmartComponent::CopyFrom(const SmartComponent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.SmartComponent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SmartComponent::InternalSwap(SmartComponent* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchange_, &other->_impl_.exchange_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchangeletter_, &other->_impl_.exchangeletter_, arena);
        swap(_impl_.bitnumber_, other->_impl_.bitnumber_);
}

::google::protobuf::Metadata SmartComponent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SmartComponent_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
