// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SmartComponents.proto
// Protobuf C++ Version: 5.29.5

#ifndef SmartComponents_2eproto_2epb_2eh
#define SmartComponents_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "SmartComponent.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SmartComponents_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SmartComponents_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SmartComponents_2eproto;
namespace protobuf {
class SmartComponents;
struct SmartComponentsDefaultTypeInternal;
extern SmartComponentsDefaultTypeInternal _SmartComponents_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class SmartComponents final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.SmartComponents) */ {
 public:
  inline SmartComponents() : SmartComponents(nullptr) {}
  ~SmartComponents() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SmartComponents* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SmartComponents));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SmartComponents(
      ::google::protobuf::internal::ConstantInitialized);

  inline SmartComponents(const SmartComponents& from) : SmartComponents(nullptr, from) {}
  inline SmartComponents(SmartComponents&& from) noexcept
      : SmartComponents(nullptr, std::move(from)) {}
  inline SmartComponents& operator=(const SmartComponents& from) {
    CopyFrom(from);
    return *this;
  }
  inline SmartComponents& operator=(SmartComponents&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SmartComponents& default_instance() {
    return *internal_default_instance();
  }
  static inline const SmartComponents* internal_default_instance() {
    return reinterpret_cast<const SmartComponents*>(
        &_SmartComponents_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SmartComponents& a, SmartComponents& b) { a.Swap(&b); }
  inline void Swap(SmartComponents* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SmartComponents* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SmartComponents* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SmartComponents>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SmartComponents& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SmartComponents& from) { SmartComponents::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SmartComponents* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.SmartComponents"; }

 protected:
  explicit SmartComponents(::google::protobuf::Arena* arena);
  SmartComponents(::google::protobuf::Arena* arena, const SmartComponents& from);
  SmartComponents(::google::protobuf::Arena* arena, SmartComponents&& from) noexcept
      : SmartComponents(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSmartComponentsFieldNumber = 2,
    kReqIdFieldNumber = 1,
  };
  // repeated .protobuf.SmartComponent smartComponents = 2;
  int smartcomponents_size() const;
  private:
  int _internal_smartcomponents_size() const;

  public:
  void clear_smartcomponents() ;
  ::protobuf::SmartComponent* mutable_smartcomponents(int index);
  ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>* mutable_smartcomponents();

  private:
  const ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>& _internal_smartcomponents() const;
  ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>* _internal_mutable_smartcomponents();
  public:
  const ::protobuf::SmartComponent& smartcomponents(int index) const;
  ::protobuf::SmartComponent* add_smartcomponents();
  const ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>& smartcomponents() const;
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.SmartComponents)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SmartComponents& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::protobuf::SmartComponent > smartcomponents_;
    ::int32_t reqid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SmartComponents_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SmartComponents

// optional int32 reqId = 1;
inline bool SmartComponents::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SmartComponents::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t SmartComponents::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.SmartComponents.reqId)
  return _internal_reqid();
}
inline void SmartComponents::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:protobuf.SmartComponents.reqId)
}
inline ::int32_t SmartComponents::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void SmartComponents::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// repeated .protobuf.SmartComponent smartComponents = 2;
inline int SmartComponents::_internal_smartcomponents_size() const {
  return _internal_smartcomponents().size();
}
inline int SmartComponents::smartcomponents_size() const {
  return _internal_smartcomponents_size();
}
inline ::protobuf::SmartComponent* SmartComponents::mutable_smartcomponents(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:protobuf.SmartComponents.smartComponents)
  return _internal_mutable_smartcomponents()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>* SmartComponents::mutable_smartcomponents()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:protobuf.SmartComponents.smartComponents)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_smartcomponents();
}
inline const ::protobuf::SmartComponent& SmartComponents::smartcomponents(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.SmartComponents.smartComponents)
  return _internal_smartcomponents().Get(index);
}
inline ::protobuf::SmartComponent* SmartComponents::add_smartcomponents() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::protobuf::SmartComponent* _add = _internal_mutable_smartcomponents()->Add();
  // @@protoc_insertion_point(field_add:protobuf.SmartComponents.smartComponents)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>& SmartComponents::smartcomponents() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:protobuf.SmartComponents.smartComponents)
  return _internal_smartcomponents();
}
inline const ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>&
SmartComponents::_internal_smartcomponents() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.smartcomponents_;
}
inline ::google::protobuf::RepeatedPtrField<::protobuf::SmartComponent>*
SmartComponents::_internal_mutable_smartcomponents() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.smartcomponents_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SmartComponents_2eproto_2epb_2eh
