// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SymbolSamples.proto
// Protobuf C++ Version: 5.29.5

#include "SymbolSamples.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr SymbolSamples::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        contractdescriptions_{},
        reqid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SymbolSamples::SymbolSamples(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SymbolSamplesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SymbolSamplesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SymbolSamplesDefaultTypeInternal() {}
  union {
    SymbolSamples _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SymbolSamplesDefaultTypeInternal _SymbolSamples_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SymbolSamples_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SymbolSamples_2eproto = nullptr;
const ::uint32_t
    TableStruct_SymbolSamples_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::SymbolSamples, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::SymbolSamples, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::SymbolSamples, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::SymbolSamples, _impl_.contractdescriptions_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::protobuf::SymbolSamples)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_SymbolSamples_default_instance_._instance,
};
const char descriptor_table_protodef_SymbolSamples_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023SymbolSamples.proto\022\010protobuf\032\031Contrac"
    "tDescription.proto\"j\n\rSymbolSamples\022\022\n\005r"
    "eqId\030\001 \001(\005H\000\210\001\001\022;\n\024contractDescriptions\030"
    "\002 \003(\0132\035.protobuf.ContractDescriptionB\010\n\006"
    "_reqIdB=\n\026com.ib.client.protobufB\022Symbol"
    "SamplesProto\252\002\016IBApi.protobufb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_SymbolSamples_2eproto_deps[1] =
    {
        &::descriptor_table_ContractDescription_2eproto,
};
static ::absl::once_flag descriptor_table_SymbolSamples_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SymbolSamples_2eproto = {
    false,
    false,
    237,
    descriptor_table_protodef_SymbolSamples_2eproto,
    "SymbolSamples.proto",
    &descriptor_table_SymbolSamples_2eproto_once,
    descriptor_table_SymbolSamples_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_SymbolSamples_2eproto::offsets,
    file_level_enum_descriptors_SymbolSamples_2eproto,
    file_level_service_descriptors_SymbolSamples_2eproto,
};
namespace protobuf {
// ===================================================================

class SymbolSamples::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SymbolSamples>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_._has_bits_);
};

void SymbolSamples::clear_contractdescriptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contractdescriptions_.Clear();
}
SymbolSamples::SymbolSamples(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.SymbolSamples)
}
inline PROTOBUF_NDEBUG_INLINE SymbolSamples::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::SymbolSamples& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        contractdescriptions_{visibility, arena, from.contractdescriptions_} {}

SymbolSamples::SymbolSamples(
    ::google::protobuf::Arena* arena,
    const SymbolSamples& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SymbolSamples* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.reqid_ = from._impl_.reqid_;

  // @@protoc_insertion_point(copy_constructor:protobuf.SymbolSamples)
}
inline PROTOBUF_NDEBUG_INLINE SymbolSamples::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        contractdescriptions_{visibility, arena} {}

inline void SymbolSamples::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reqid_ = {};
}
SymbolSamples::~SymbolSamples() {
  // @@protoc_insertion_point(destructor:protobuf.SymbolSamples)
  SharedDtor(*this);
}
inline void SymbolSamples::SharedDtor(MessageLite& self) {
  SymbolSamples& this_ = static_cast<SymbolSamples&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SymbolSamples::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SymbolSamples(arena);
}
constexpr auto SymbolSamples::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_.contractdescriptions_) +
          decltype(SymbolSamples::_impl_.contractdescriptions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SymbolSamples), alignof(SymbolSamples), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SymbolSamples::PlacementNew_,
                                 sizeof(SymbolSamples),
                                 alignof(SymbolSamples));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SymbolSamples::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SymbolSamples_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SymbolSamples::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SymbolSamples>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SymbolSamples::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SymbolSamples>(), &SymbolSamples::ByteSizeLong,
            &SymbolSamples::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_._cached_size_),
        false,
    },
    &SymbolSamples::kDescriptorMethods,
    &descriptor_table_SymbolSamples_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SymbolSamples::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> SymbolSamples::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::SymbolSamples>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .protobuf.ContractDescription contractDescriptions = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_.contractdescriptions_)}},
    // optional int32 reqId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SymbolSamples, _impl_.reqid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_.reqid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 reqId = 1;
    {PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_.reqid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .protobuf.ContractDescription contractDescriptions = 2;
    {PROTOBUF_FIELD_OFFSET(SymbolSamples, _impl_.contractdescriptions_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::protobuf::ContractDescription>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SymbolSamples::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.SymbolSamples)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.contractdescriptions_.Clear();
  _impl_.reqid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SymbolSamples::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SymbolSamples& this_ = static_cast<const SymbolSamples&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SymbolSamples::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SymbolSamples& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.SymbolSamples)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 reqId = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_reqid(), target);
          }

          // repeated .protobuf.ContractDescription contractDescriptions = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_contractdescriptions_size());
               i < n; i++) {
            const auto& repfield = this_._internal_contractdescriptions().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.SymbolSamples)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SymbolSamples::ByteSizeLong(const MessageLite& base) {
          const SymbolSamples& this_ = static_cast<const SymbolSamples&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SymbolSamples::ByteSizeLong() const {
          const SymbolSamples& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.SymbolSamples)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .protobuf.ContractDescription contractDescriptions = 2;
            {
              total_size += 1UL * this_._internal_contractdescriptions_size();
              for (const auto& msg : this_._internal_contractdescriptions()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // optional int32 reqId = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reqid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SymbolSamples::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SymbolSamples*>(&to_msg);
  auto& from = static_cast<const SymbolSamples&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.SymbolSamples)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_contractdescriptions()->MergeFrom(
      from._internal_contractdescriptions());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.reqid_ = from._impl_.reqid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SymbolSamples::CopyFrom(const SymbolSamples& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.SymbolSamples)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SymbolSamples::InternalSwap(SymbolSamples* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.contractdescriptions_.InternalSwap(&other->_impl_.contractdescriptions_);
        swap(_impl_.reqid_, other->_impl_.reqid_);
}

::google::protobuf::Metadata SymbolSamples::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SymbolSamples_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
