// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WshEventDataRequest.proto
// Protobuf C++ Version: 5.29.5

#include "WshEventDataRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr WshEventDataRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filter_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        startdate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        enddate_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reqid_{0},
        conid_{0},
        fillwatchlist_{false},
        fillportfolio_{false},
        fillcompetitors_{false},
        totallimit_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WshEventDataRequest::WshEventDataRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WshEventDataRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WshEventDataRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WshEventDataRequestDefaultTypeInternal() {}
  union {
    WshEventDataRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WshEventDataRequestDefaultTypeInternal _WshEventDataRequest_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_WshEventDataRequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_WshEventDataRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_WshEventDataRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.conid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.filter_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.fillwatchlist_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.fillportfolio_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.fillcompetitors_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.startdate_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.enddate_),
        PROTOBUF_FIELD_OFFSET(::protobuf::WshEventDataRequest, _impl_.totallimit_),
        3,
        4,
        0,
        5,
        6,
        7,
        1,
        2,
        8,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 17, -1, sizeof(::protobuf::WshEventDataRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_WshEventDataRequest_default_instance_._instance,
};
const char descriptor_table_protodef_WshEventDataRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031WshEventDataRequest.proto\022\010protobuf\"\357\002"
    "\n\023WshEventDataRequest\022\022\n\005reqId\030\001 \001(\005H\000\210\001"
    "\001\022\022\n\005conId\030\002 \001(\005H\001\210\001\001\022\023\n\006filter\030\003 \001(\tH\002\210"
    "\001\001\022\032\n\rfillWatchlist\030\004 \001(\010H\003\210\001\001\022\032\n\rfillPo"
    "rtfolio\030\005 \001(\010H\004\210\001\001\022\034\n\017fillCompetitors\030\006 "
    "\001(\010H\005\210\001\001\022\026\n\tstartDate\030\007 \001(\tH\006\210\001\001\022\024\n\007endD"
    "ate\030\010 \001(\tH\007\210\001\001\022\027\n\ntotalLimit\030\t \001(\005H\010\210\001\001B"
    "\010\n\006_reqIdB\010\n\006_conIdB\t\n\007_filterB\020\n\016_fillW"
    "atchlistB\020\n\016_fillPortfolioB\022\n\020_fillCompe"
    "titorsB\014\n\n_startDateB\n\n\010_endDateB\r\n\013_tot"
    "alLimitBC\n\026com.ib.client.protobufB\030WshEv"
    "entDataRequestProto\252\002\016IBApi.protobufb\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_WshEventDataRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_WshEventDataRequest_2eproto = {
    false,
    false,
    484,
    descriptor_table_protodef_WshEventDataRequest_2eproto,
    "WshEventDataRequest.proto",
    &descriptor_table_WshEventDataRequest_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_WshEventDataRequest_2eproto::offsets,
    file_level_enum_descriptors_WshEventDataRequest_2eproto,
    file_level_service_descriptors_WshEventDataRequest_2eproto,
};
namespace protobuf {
// ===================================================================

class WshEventDataRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<WshEventDataRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_._has_bits_);
};

WshEventDataRequest::WshEventDataRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.WshEventDataRequest)
}
inline PROTOBUF_NDEBUG_INLINE WshEventDataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::WshEventDataRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filter_(arena, from.filter_),
        startdate_(arena, from.startdate_),
        enddate_(arena, from.enddate_) {}

WshEventDataRequest::WshEventDataRequest(
    ::google::protobuf::Arena* arena,
    const WshEventDataRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WshEventDataRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, reqid_),
           offsetof(Impl_, totallimit_) -
               offsetof(Impl_, reqid_) +
               sizeof(Impl_::totallimit_));

  // @@protoc_insertion_point(copy_constructor:protobuf.WshEventDataRequest)
}
inline PROTOBUF_NDEBUG_INLINE WshEventDataRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        filter_(arena),
        startdate_(arena),
        enddate_(arena) {}

inline void WshEventDataRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqid_),
           0,
           offsetof(Impl_, totallimit_) -
               offsetof(Impl_, reqid_) +
               sizeof(Impl_::totallimit_));
}
WshEventDataRequest::~WshEventDataRequest() {
  // @@protoc_insertion_point(destructor:protobuf.WshEventDataRequest)
  SharedDtor(*this);
}
inline void WshEventDataRequest::SharedDtor(MessageLite& self) {
  WshEventDataRequest& this_ = static_cast<WshEventDataRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filter_.Destroy();
  this_._impl_.startdate_.Destroy();
  this_._impl_.enddate_.Destroy();
  this_._impl_.~Impl_();
}

inline void* WshEventDataRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) WshEventDataRequest(arena);
}
constexpr auto WshEventDataRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WshEventDataRequest),
                                            alignof(WshEventDataRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull WshEventDataRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_WshEventDataRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &WshEventDataRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<WshEventDataRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &WshEventDataRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<WshEventDataRequest>(), &WshEventDataRequest::ByteSizeLong,
            &WshEventDataRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_._cached_size_),
        false,
    },
    &WshEventDataRequest::kDescriptorMethods,
    &descriptor_table_WshEventDataRequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* WshEventDataRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 67, 2> WshEventDataRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::WshEventDataRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 reqId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WshEventDataRequest, _impl_.reqid_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.reqid_)}},
    // optional int32 conId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WshEventDataRequest, _impl_.conid_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.conid_)}},
    // optional string filter = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.filter_)}},
    // optional bool fillWatchlist = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WshEventDataRequest, _impl_.fillwatchlist_), 5>(),
     {32, 5, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillwatchlist_)}},
    // optional bool fillPortfolio = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WshEventDataRequest, _impl_.fillportfolio_), 6>(),
     {40, 6, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillportfolio_)}},
    // optional bool fillCompetitors = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WshEventDataRequest, _impl_.fillcompetitors_), 7>(),
     {48, 7, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillcompetitors_)}},
    // optional string startDate = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 1, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.startdate_)}},
    // optional string endDate = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 2, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.enddate_)}},
    // optional int32 totalLimit = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WshEventDataRequest, _impl_.totallimit_), 8>(),
     {72, 8, 0, PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.totallimit_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 reqId = 1;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.reqid_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 conId = 2;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.conid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string filter = 3;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.filter_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional bool fillWatchlist = 4;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillwatchlist_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool fillPortfolio = 5;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillportfolio_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool fillCompetitors = 6;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.fillcompetitors_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional string startDate = 7;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.startdate_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string endDate = 8;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.enddate_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 totalLimit = 9;
    {PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.totallimit_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\34\0\0\6\0\0\0\11\7\0\0\0\0\0\0\0"
    "protobuf.WshEventDataRequest"
    "filter"
    "startDate"
    "endDate"
  }},
};

PROTOBUF_NOINLINE void WshEventDataRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.WshEventDataRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.filter_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.startdate_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.enddate_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&_impl_.reqid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.fillcompetitors_) -
        reinterpret_cast<char*>(&_impl_.reqid_)) + sizeof(_impl_.fillcompetitors_));
  }
  _impl_.totallimit_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* WshEventDataRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const WshEventDataRequest& this_ = static_cast<const WshEventDataRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* WshEventDataRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const WshEventDataRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.WshEventDataRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 reqId = 1;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_reqid(), target);
          }

          // optional int32 conId = 2;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_conid(), target);
          }

          // optional string filter = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_filter();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.WshEventDataRequest.filter");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // optional bool fillWatchlist = 4;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_fillwatchlist(), target);
          }

          // optional bool fillPortfolio = 5;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_fillportfolio(), target);
          }

          // optional bool fillCompetitors = 6;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_fillcompetitors(), target);
          }

          // optional string startDate = 7;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_startdate();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.WshEventDataRequest.startDate");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // optional string endDate = 8;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_enddate();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.WshEventDataRequest.endDate");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // optional int32 totalLimit = 9;
          if (cached_has_bits & 0x00000100u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<9>(
                    stream, this_._internal_totallimit(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.WshEventDataRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t WshEventDataRequest::ByteSizeLong(const MessageLite& base) {
          const WshEventDataRequest& this_ = static_cast<const WshEventDataRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t WshEventDataRequest::ByteSizeLong() const {
          const WshEventDataRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.WshEventDataRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string filter = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filter());
            }
            // optional string startDate = 7;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_startdate());
            }
            // optional string endDate = 8;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_enddate());
            }
            // optional int32 reqId = 1;
            if (cached_has_bits & 0x00000008u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reqid());
            }
            // optional int32 conId = 2;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_conid());
            }
            // optional bool fillWatchlist = 4;
            if (cached_has_bits & 0x00000020u) {
              total_size += 2;
            }
            // optional bool fillPortfolio = 5;
            if (cached_has_bits & 0x00000040u) {
              total_size += 2;
            }
            // optional bool fillCompetitors = 6;
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
           {
            // optional int32 totalLimit = 9;
            if (cached_has_bits & 0x00000100u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_totallimit());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void WshEventDataRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WshEventDataRequest*>(&to_msg);
  auto& from = static_cast<const WshEventDataRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.WshEventDataRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_filter(from._internal_filter());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_startdate(from._internal_startdate());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_enddate(from._internal_enddate());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.reqid_ = from._impl_.reqid_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.conid_ = from._impl_.conid_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.fillwatchlist_ = from._impl_.fillwatchlist_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.fillportfolio_ = from._impl_.fillportfolio_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.fillcompetitors_ = from._impl_.fillcompetitors_;
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_impl_.totallimit_ = from._impl_.totallimit_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WshEventDataRequest::CopyFrom(const WshEventDataRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.WshEventDataRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WshEventDataRequest::InternalSwap(WshEventDataRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filter_, &other->_impl_.filter_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.startdate_, &other->_impl_.startdate_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.enddate_, &other->_impl_.enddate_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.totallimit_)
      + sizeof(WshEventDataRequest::_impl_.totallimit_)
      - PROTOBUF_FIELD_OFFSET(WshEventDataRequest, _impl_.reqid_)>(
          reinterpret_cast<char*>(&_impl_.reqid_),
          reinterpret_cast<char*>(&other->_impl_.reqid_));
}

::google::protobuf::Metadata WshEventDataRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_WshEventDataRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
